### PR TITLE
Embedded Video which starts after user scrolls down.

### PR DESCRIPTION
**Pull request by jbicker**
Fixes https://github.com/gitpod-io/website/issues/718

### CODE REVIEW

**Comment by nisarhassan12** [comment]
On mobile, the video is overlapping with the heading "Trsuted By" visionary teams.

image
image

**Comment by jbicker** [comment]
Good catch. I am correcting it.

**Comment by jbicker** [comment]
Is fine now.

**Comment by nisarhassan12** [comment]
Also currently on not too fast internet connections when the video first loads a quite smaller container with the browser Ui shows up may let's make that also take up the width that it takes when the videos loads as the flicker from small to big maybe does not look that great.

image

**Comment by svenefftinge** [comment]
We decided not to go with this animation.

**Pull request closed without merging**
