### PR TITLE
remove the newsletter form for now as the functionality does not work.

### PR DESCRIPTION
**Pull request by nisarhassan12**

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Thanks! @JesterOrNot I think this is worth fixing but would make sense to have to remove from the production site unless it's fixed.

**Comment by JesterOrNot** [comment]
In that case, let's add a maintenance message saying something like hey 'the newsletter is under maintenance please check back soon!'

**Comment by JesterOrNot** [comment]
And let's comment it out instead of flat out removing it.

**Comment by nisarhassan12** [comment]
Thanks! commenting is a good idea. 

> In that case, let's add a maintenance message saying something like hey 'the newsletter is under maintenance please check back soon!

Let's open a Github issue for this instead as discussed on Slack.

**Pull request merged**
