### PR TITLE
Performance: use `lite-youtube-embed` instead of `<iframe>`

### LINKED ISSUE #1175: [Docs - New Feature]: Lighter YouTube Embeds
### Describe your feature

The YouTube Embeds provided by YouTube themselves are extremely slow, I really mean that, even Google themselves suggest using a different one. The one they're suggesting is https://github.com/paulirish/lite-youtube-embed. It's about 200 times faster than the official one. There is basically no downside to this, less stuff is preloaded for the initial load so people who don't intend on playing the video in the first place don't have to pay the cost of all the bandwidth needed for the embed. 

https://github.com/gitpod-io/website/blob/main/src/components/youtube-embed.svelte

### How to test

Open a page like https://www.gitpod.io/docs/getting-started and in the Network tab of the DevTools see the change in bandwidth consumed.

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

This PR Introduces the use of [`lite-youtube-embed`](https://www.npmjs.com/package/svelte-lite-youtube-embed) package, instead of using default `<iframe>` to render YT Videos.

## Related Issue(s)

Fixes #1175

## How to test

- Open Netlify Preview
- Go To [`/docs`](https://deploy-preview-2971--gitpod-kumquat.netlify.app/docs/introduction/getting-started), [`/screencasts`](https://deploy-preview-2971--gitpod-kumquat.netlify.app/screencasts), [`/guides`](https://deploy-preview-2971--gitpod-kumquat.netlify.app/guides), [`/webinars/java-panel-discussion`](https://deploy-preview-2971--gitpod-kumquat.netlify.app/webinars/java-panel-discussion) & other pages which have YT Embeds

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2971"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2971"></a>

### CODE REVIEW

**Review by chrifro — APPROVED** [review]
Looks great to me. 

Small note:
the rounded corners of the video have a tiny border outline. Which wasn't there before. Could you remove that line?

Bildschirmfoto 2022-11-14 um 15 04 25

**Comment by Siddhant-K-code** [comment]
I tried to minified it: 

image

I don't think we can remove it by 100%. We are embedding YT Component over card. I think, it's good for now 🤔 

WDYT @Cahllagerfeld, @chrifro?

**Comment by Siddhant-K-code** [comment]
It is also [already there](https://www.gitpod.io/docs/integrations/jetbrains-gateway#setting-a-jetbrains-ide-as-a-preference)

image

**Review by Cahllagerfeld — APPROVED** [review]

**Comment by filiptronicek** [comment]
@Siddhant-K-code thanks a lot for this, it was on my wishlist for the website for quite a while! 🙏 🎉

**Pull request merged**
