### PR TITLE
/pricing and /self-hosted imrpovements.

### LINKED ISSUE #1404: /pricing improvements
Great to see that the new pricing page is implemented. Here are a few more things that need to be addressed.

**General:**

- [ ] use a switch instead of the toggle #1387
- [x] pricing cards: align text to the center and reduce spacing (see mockup)
Bildschirmfoto 2021-12-28 um 11 29 52

- [x] tooltips: move tooltips above the icon instead of underneath, update the layout (bubble style), color - what do you think about using a dark background? (see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=2828%3A1288), see [GitHub](https://github.com/pricing) for inspiration)
- [ ] #1416
Bildschirmfoto 2021-12-28 um 11 42 39

- [x] link "view requirements" to https://www.gitpod.io/docs/professional-open-source
- [x] add a pop-up to redeem student offer. Currently, there is no link❗️
Bildschirmfoto 2021-12-28 um 11 46 42

- [x]  FAQs: add new items based on the Figma comments, update the current FAQs (e.g. link to student plan is outdated)
- [x] Self-hosted: Why is there a "+"? it can be removed
Bildschirmfoto 2021-12-28 um 11 54 32

**Mobile:**

- [x] could you shorten the text to "get started" on mobile? By that we reduce vertical space. Alternatively, move "for" to the next line
Bildschirmfoto 2021-12-28 um 11 52 29

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #1404 

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1415"></a>

### CODE REVIEW

**Review by ChristinFrohne — CHANGES_REQUESTED** [review]
Thanks! Some comments:
- [x] the spacing in the pricing card still needs to be adjusted. In the mockup it's 24px between "user/month" and the first feature and the same for the spacing above the CTA. below the CTA it's 48px just like the top of the card. Any reason why you didn't use that?
Bildschirmfoto 2022-01-04 um 14 29 33

- [ ] the tooltip peak should point on the icon (see mockup)
Bildschirmfoto 2022-01-04 um 14 27 30

- [ ] can you adjust the width of the tooltip to fit the text? 

- [ ] FAQs: "See Gitpod for Students for more information." still has the wrong link. Can you link it to the popup? If not, link to the "we love to empower creative minds" section

- [x] there is still lots of horizontal spacing between the categories and the cards in the table. Could you reduce the spacing?
Bildschirmfoto 2022-01-04 um 14 33 29
 

- [ ] have "self-hosted" in one row on mobile
Bildschirmfoto 2022-01-04 um 14 35 20

**Comment by nisarhassan12** [comment]
> - [ ]  the tooltip peak should point on the icon (see mockup)

@ChristinFrohne as we already discussed in the call it is not easy to achieve i.e I tried moving the content to the right of the peak but that does not work consistently well specifically for the list items that have less text content like the one shown below:

image

> - []  can you adjust the width of the tooltip to fit the text?

we also discussed in the call that this is not possible as well i.e this way the text will go off the screen on various screen sizes. 

> - []  there is still lots of horizontal spacing between the categories and the cards in the table. Could you reduce the spacing?

This is gonna be addressed as part of https://github.com/gitpod-io/website/issues/1384

**Comment by ChristinFrohne** [comment]
Currently, the tooltip layout with the peak pointing nowhere doesn't make sense. 

I updated the specs [here](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Website-Component-Library?node-id=518%3A1074), inspired by the GitHub product specs. Does that help? 

If you can't find a solution, we need to implement it without the peak for now.

Also, can you add a hover style for the toggle based on [these specs](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Website-Component-Library?node-id=513%3A527)?

**Comment by nisarhassan12** [comment]
> If you can't find a solution, we need to implement it without the peak for now.

@ChristinFrohne I'm not able to find a solution that works well across all of the instances so I have removed the peak. 

> Also, can you add a hover style for the toggle based on these specs?

Done ✅

**Comment by mikenikles** [comment]
@nisarhassan12 Would a tooltip component like this work? https://github.com/fouita/svelte-tw-tooltip

**Comment by nisarhassan12** [comment]
Thanks, @mikenikles for sharing this. It is not gonna work for us the reason is the lack of customizations options i.e you can only change the colour and the text colour and most importantly it is not gonna solve `the tooltip peak should point on the icon` specified above the challenging part is the varying positioning in accordance to the content size.  

image

**Review by ChristinFrohne — APPROVED** [review]
I'd say let's merge this PR and see if we can optimize the tooltips in another PR. Other websites use similar tooltips, so there must be a way to figure this out e.g. GitHub. It would also be great to adjust the width based on the text length
|desktop|tablet|
|-|-|
|Bildschirmfoto 2022-01-11 um 10 08 46|Bildschirmfoto 2022-01-11 um 10 08 33|
|Bildschirmfoto 2022-01-11 um 10 14 04

- [x] Could you open a follow-up issue for that @nisarhassan12 ✅ ?

- [ ] please check that all tooltips start with a capital letter before merging it

**Pull request merged**
