### PR TITLE
fix(gitpodify): Update outdated `postgres` image pointer

### PR DESCRIPTION
**Pull request by axonasif**
## Related Issue(s)

Fixes:
- https://app.frontapp.com/open/cnv_jgtwksq
- https://discord.com/channels/816244985187008514/983640504031932436

## Release Notes

```release-note
```

## Documentation

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2296"></a>

### CODE REVIEW

**Comment by axonasif** [comment]
> I wasn't even aware that we are using that base-image lol. Is there a reason, why we need to `postgres` one? 😬

Where do you mean 👀

**Comment by Cahllagerfeld** [comment]
I completely messed up 🤦. I thought you adjusted the `.gitpod.yml`.. I just realized it's a blog post...

**Comment by Cahllagerfeld** [comment]
Isn't [this](https://hub.docker.com/r/gitpod/workspace-postgres) the image, that's required as the base image in our scenario? Given this assumption the previous image name was correct, wasn't it? I think the `postgres` image got updated more recently than the [postgresql](https://hub.docker.com/r/gitpod/workspace-postgresql) one

**Comment by axonasif** [comment]
> Isn't [this](https://hub.docker.com/r/gitpod/workspace-postgres) the image, that's required as the base image in our scenario? Given this assumption the previous image name was correct, wasn't it? I think the `postgres` image got updated more recently than the [postgresql](https://hub.docker.com/r/gitpod/workspace-postgresql) one

In terms of automatic dockerhub pushes, yeah, that's more updo date regardless of changes in the actual dockerfile.

But that really doesn't matter when you compare the source of [postgresql](https://github.com/gitpod-io/workspace-images/blob/main/chunks/tool-postgresql/Dockerfile) and the legacy [postgres](https://github.com/gitpod-io/workspace-images/blob/main/legacy/postgres/Dockerfile)

**Pull request merged**
