### PR TITLE
add dark theme.

### LINKED ISSUE #374: REQUEST: Dark theme for www.gitpod.io
I've noticed that gitpod.io is now in light theme, requesting dark theme option for people suffering from photophobia and people like me with huge screen that blinds them everytime they open a light themed window.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #374 

image

### CODE REVIEW

**Comment by RDIL** [comment]
I don't really think its worth it given this is just the marketing stuff, not the actual app.

**Comment by nisarhassan12** [comment]
Thanks, @RDIL :slightly_smiling_face:  I think the dark mode can be helpful especially for the Docs and the Blog and it's a requested feature.

**Comment by nisarhassan12** [comment]
https://github.com/gitpod-io/website/pull/557#pullrequestreview-430136859

image

**Comment by nisarhassan12** [comment]
Closing as it's too old and there are too many conflicts.

**Pull request closed without merging**
