### PR TITLE
Pin Node Version

### PR DESCRIPTION
**Pull request by Cahllagerfeld**

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
On hold until we are sure, if we really want to do this

**Comment by gtsiolis** [comment]
**fyi**: Accidentally marked this as ready for review, @Cahllagerfeld! 🏓

**Comment by Cahllagerfeld** [comment]
Don't worry, no problem. 😄 🏄‍♂️

**Comment by Cahllagerfeld** [comment]
closing this, as its currently not needed

**Pull request closed without merging**
