### PR TITLE
📄 docs: start workspace with options modal

### LINKED ISSUE #3358: [Docs] Start With Options
### Description

Document the implementation done in https://github.com/gitpod-io/gitpod/pull/15567 

image

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

Documentation for "start a Gitpod workspace with options" modal

## Related Issue(s)

Fixes #3358

## How to test

Open Preview:

- [Getting Started](https://deploy-preview-3361--gitpod-kumquat.netlify.app/docs/introduction/getting-started#start-your-first-workspace)
- [IDEs and Editors](https://deploy-preview-3361--gitpod-kumquat.netlify.app/docs/references/ides-and-editors#start-a-workspace-with-an-ideeditor)
- [VS Code](https://deploy-preview-3361--gitpod-kumquat.netlify.app/docs/references/ides-and-editors/vscode#open-vs-code-desktop-from-the-gitpod-dashboard)
- [Workspace classes](https://deploy-preview-3361--gitpod-kumquat.netlify.app/docs/configure/workspaces/workspace-classes#select-a-workspace-class-for-your-workspace)

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3361"></a>

### CODE REVIEW

**Comment by atduarte** [comment]
@Siddhant-K-code I'm afraid this is a bit overwhelming for the "getting started". Do you see any other place that could make sense to add this information?

**Comment by Siddhant-K-code** [comment]
@atduarte I didn't find anything 😅 

image

**Comment by loujaybee** [comment]
> @Siddhant-K-code I'm afraid this is a bit overwhelming for the "getting started". Do you see any other place that could make sense to add this information? - @atduarte 

I do agree with this. Getting started should be very short + direct (it's already too verbose). See also: 

- https://github.com/gitpod-io/website/issues/3019

**Some options:** 

* **[/docs/introduction/learn-gitpod](https://www.gitpod.io/docs/configure/workspaces)** => We could have a high level page here "using workspaces", "developing with workspaces", or "your first workspace" that covers ways to manage your workspaces generally and covering: dashboard, browser extension, etc. This could be included as one of the ways...
* **[/docs/configure/workspaces/workspace-lifecycle](https://www.gitpod.io/docs/configure/workspaces/workspace-lifecycle#workspace-starting)** => We could extend or add this to the workspace lifecycle page. We already have a workspace starting section, we could add some screenshots for the ways users could start a new workspace here. 
* **[/docs/configure/workspaces](https://www.gitpod.io/docs/configure/workspaces)** => We could add a page here for general workspace management, however this would probably overlap with the previous page. 

Personally, I have to "see" a docs change like this in action/context to really know how I feel about the content placement and flow, but wanted to at least offer some ideas.

**Comment by Siddhant-K-code** [comment]
Thanks for the thoughts @atduarte & @loujaybee. Feel free to restructure it the newer place 🙏🏽

**Comment by Siddhant-K-code** [comment]
From Dashboard (`Learn more`), We point to [this page - getting started](https://www.gitpod.io/docs/introduction/getting-started):

image

**Comment by loujaybee** [comment]
> Thanks for the thoughts @atduarte & @loujaybee. Feel free to restructure it to the newer place 🙏🏽

Could you put some time on my calendar, @Siddhant-K-code ? Let's look through it together, and get this unblocked.

**Comment by Siddhant-K-code** [comment]
> Could you put some time on my calendar, @Siddhant-K-code 

Invite sent @loujaybee 😃

**Comment by loujaybee** [comment]
Discussion with @Siddhant-K-code: 

In this PR: 
- Add to: https://www.gitpod.io/docs/configure/workspaces/workspace-classes
- Add to: https://www.gitpod.io/docs/references/ides-and-editors/vscode#open-a-workspace-in-vs-code-desktop
- Add to: https://www.gitpod.io/docs/references/ides-and-editors

In a separate PR: 
- Document URL parameters

**Comment by Siddhant-K-code** [comment]
Updated the changes. Previews:

- [Getting Started](https://deploy-preview-3361--gitpod-kumquat.netlify.app/docs/introduction/getting-started#start-your-first-workspace)
- [IDEs and Editors](https://deploy-preview-3361--gitpod-kumquat.netlify.app/docs/references/ides-and-editors#start-a-workspace-with-an-ideeditor)
- [VS Code](https://deploy-preview-3361--gitpod-kumquat.netlify.app/docs/references/ides-and-editors/vscode#open-vs-code-desktop-from-the-gitpod-dashboard)
- [Workspace classes](https://deploy-preview-3361--gitpod-kumquat.netlify.app/docs/configure/workspaces/workspace-classes#select-a-workspace-class-for-your-workspace)

_// cc: @atduarte @loujaybee_

**Review by geropl — APPROVED** [review]
LGTM!

**Pull request merged**
