### PR TITLE
Mastodon Link

### LINKED ISSUE #3223: Add Mastodon Link
### Description

We now have a Mastodon account so we should link to it on the Footer of the website (this also allows for us to validate we own gitpod.io on Mastodon) and any other relevant pages

### PR DESCRIPTION
**Pull request by ghostdevv**
## Description

If there is any other pages this link should be on let me know and I will update the pr

## Related Issue(s)

Fixes #3223

## How to test

Check the footer

## Release Notes

```release-note
added mastodon link to footer
```

### CODE REVIEW

**Comment by ghostdevv** [comment]
@Siddhant-K-code We will be keeping our Twitter and Mastodon account up to date going forward - this is part of the steps before we can start doing that

**Comment by Siddhant-K-code** [comment]
Converting this PR to draft, until we get final process to this https://github.com/gitpod-io/website/issues/3223#issuecomment-1411477618

**Review by MichaelAring — APPROVED** [review]

**Comment by MichaelAring** [comment]
Apologies for the slow response time, everyone! Looks good to me.

**Comment by pawlean** [comment]
I vote that we don't have this on the website as we are not actively using it, however, we should add our bluesky account. I opened [this issue](https://github.com/gitpod-io/community/issues/29), @ghostdevv can you take this on?

**Pull request closed without merging**
