### PR TITLE
:sparkles: Cleanup Get Started section

### LINKED ISSUE #3381: Polish "get started" section
**Tasks**

- [x] align button height to 48px for both "continue with XYZ" and the workspace examples
- [ ] update logos for the example workspaces -> color and sizes (see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=8898%3A17416&t=hnSPrZItohUwUOAC-1))
- [x] increase spacing in front of the example workspace logos to align with the mockup

|status quo| mockup|
|-|-|
|Bildschirm­foto 2023-02-06 um 11 19 06|Bildschirm­foto 2023-02-06 um 11 19 10

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

|Before|After|
|:---:|:---:|
|image|image|

Regarding Renaming, see https://github.com/gitpod-io/website/issues/3372#issuecomment-1416100512

## Related Issue(s)

Fixes #3381

## How to test

- Open Preview, Scroll down to Bottom of the homepage

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3411"></a>

### CODE REVIEW

**Review by chrifro — COMMENTED** [review]
Nice, thanks for picking up this polishing task ✨

could you align the logo size and color as well?
color: #666564 for the default state
|preview| mockup|
|-|-|
|Bildschirm­foto 2023-02-09 um 21 09 16|Bildschirm­foto 2023-02-09 um 21 10 21

Feel free to merge it afterward

**Comment by Siddhant-K-code** [comment]
@chrifro, I've tried to resize. All Logos are looking good now, except Go (there is some more empty space on top & bottom - but that's just their logo 😅)


image


Regarding `grayscale`. We are already applying the filter to an SVG and removing it on on hover/focus. I don't think, we should modify the color of "trademark logo". So as it is good by not changing the fill colors (e.g. `#666564`) & just apply filter.

**Suggestion**:

All Colorful Logos (like we have for GitLab, GitHub, Bitbucket) by default:

image

**Comment by chrifro** [comment]
The rust logo sticks out too much compared to other logos and could be toned down. 

Anyway, this shouldn't be a blocker. Your call

**Comment by Siddhant-K-code** [comment]
> The rust logo sticks out too much compared to other logos

yeah, it wins the contrast over Go, and it got hidden 😓

**Comment by Siddhant-K-code** [comment]
Let's keep it grayscale only, it will push the user to hover so that the `Launch Workspace` button would get active. We should also think that button, it's should be a CTA (not behind the hover)

**Pull request merged**
