### PR TITLE
posts: size and space headlines consistently.

### LINKED ISSUE #2130: Update header 4 tags
### Page URL

all

### User feedback

H4 tags are styled larger than H3, can we adjust so they're incrementally formatted? 

I'd suggest also an incrementally decreasing margin top between headers. As an example…

h2 has margin-top: 50px
h3 has margin-top: 40px
h4 has margin-top: 30px

Why? Because the consistent margin makes it feel like the nested content is in fact a new section.

image

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #2130 

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2176"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2176"></a>

### CODE REVIEW

**Comment by nisarhassan12** [comment]
image

@chrifro According to the specs it works well for the docs but needs some adjustments for `/blog`, `/customers`, `/guides` and so on i.e the `72px` spacing at the top does not work well + the size of the quotes might need to be reduced by a bit. 

image

image

**Comment by nisarhassan12** [comment]
Thanks, @chrifro I have reverted my change for the blog, guides and docs i.e the h1 there no longer has the 72px at the top. 

> In the preview, it still uses exactly the same spacing as in the live version. Did you decide not to adjust them?

It was using the new version but the paragraphs below the headings had a margin-top which I have removed now.

**Comment by chrifro** [comment]
Sometimes the spacing between the paragraphs seems a bit tight. Let's increase it a bit with the [following margins](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=2052%3A3285)
Bildschirmfoto 2022-06-10 um 08 54 26


Example where the spacing is too tight:
Bildschirmfoto 2022-06-10 um 08 53 16

**Comment by nisarhassan12** [comment]
> Let's increase it a bit with the [following margins](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=2052%3A3285)

@chrifro please have a look at this comment https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV?node-id=2052:3285#209353544  I'm unable to extract the spacing.

**Comment by nisarhassan12** [comment]
@chrifro I have updated the Pr as per the recent Figma comments please have a look when you get time. Thanks 

Also please make sure to review the spacings/sizing on mobile for the docs and blog.

**Review by chrifro — APPROVED** [review]
Thanks, LGTM ✨

**Pull request merged**
