### PR TITLE
:sparkles: Revamp `/cde` page

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

Revamp `/CDE` page

## Related Issue(s)

Fixes MKWEB-25

## How to test

- Open preview
- Go to `/cde`
- See 👀 

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3721"></a>

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
@chrifro for this particular part. This was the I can do, I was unable to adjust the background color of the text. Can we choose some other design?

image

**Review by chrifro — APPROVED** [review]
Thanks, @Siddhant-K-code 

A few comments:

- [x] the page is not optimized for dark theme and mobile. We discussed before adding some checkboxes to the PR template to not overlook these things. What's the status on that?

Bildschirmfoto 2023-06-05 um 16 09 40
Bildschirmfoto 2023-06-05 um 16 11 51

- [x] The highlighted text doesn't seem to be responsive and it would be great to move the highlights further down (see [mockup](https://www.figma.com/file/BwA7cNkepuEqD9b39u3VQK/changes-v1?type=design&node-id=1%3A8052&t=1jTBJNCd87ldDmaV-1)). I found [this guide](https://codepen.io/alvarotrigo/pen/oNpvMbb) that might help to achieve this (without the rotation)

- [x] the spacing between the headline and the "get a demo" button is off (must have happened by mistake in Figma). Should be 32px
Bildschirmfoto 2023-06-05 um 16 10 40

**Comment by Siddhant-K-code** [comment]
> The highlighted text doesn't seem to be responsive and it would be great to move the highlights further down (see [mockup](https://www.figma.com/file/BwA7cNkepuEqD9b39u3VQK/changes-v1?type=design&node-id=1%3A8052&t=1jTBJNCd87ldDmaV-1)). I found [this guide](https://codepen.io/alvarotrigo/pen/oNpvMbb) that might help to achieve this (without the rotation)

I tried to implement it. But, for some reason, it's unnecessarily complicated!

## Desktop Light Mode

image

## Desktop Dark Mode

image


## Mobile

This would be like this: 
image

**Comment by Siddhant-K-code** [comment]
Current State as of :

## Desktop Mode (Light):
image

## Desktop Mode (Dark):
image

## Mobile mode (same for both light & dark mode - No Highlights brushes)
image

**Pull request merged**
