### PR TITLE
WIP: Improve SVGs with the Galaxy backgrounds

### LINKED ISSUE #430: [svg images] improve svg images
@jbicker could you help out with adjusting the SVG images? 

- [x] Enterprise -Globe: cut image #370

- [x] Features - Notebook: cut image #370

- [ ] recovering your old PR with the optimized SVG images 

Currently, some images have a bad quality:

Bildschirmfoto 2020-01-24 um 13 26 39

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #430

### CODE REVIEW

**Comment by nisarhassan12** [comment]
image

**Comment by nisarhassan12** [comment]
Thanks! I have made the change please have a look again 
image

**Comment by ChristinFrohne** [comment]
The quality is still really bad. The background image very pixelated. Maybe you need to down scale the image itself?

**Comment by nisarhassan12** [comment]
Are these the icons you're talking about or are there other places as well :) ?
image

**Comment by ChristinFrohne** [comment]
Almost all of them. The two are just an example. 
The icons in `select a project` look fine though and it seems like the background images are smaller inside them.

**Comment by nisarhassan12** [comment]
> Almost all of them. The two are just an example.
> The icons in `select a project` look fine though and it seems like the background images are smaller inside them.

Ok! I'll try to fix all of them soon! Thanks

**Comment by nisarhassan12** [comment]
SVGs look a lot better now because of downscaling the galaxy background:

image

**Pull request merged**
