### PR TITLE
📊 Refactor: Better analytics for A/B Testing Experiments

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

This PR introduces a new Segment event (`component_loaded`). This Would be tied to certain components (explicitly). So that, we can better track the way that which component gets loaded. For this particular case (Git Signups CTA component). We've tied this that, is it getting rendered with which property `experiments_variant` which would have two possible values: `git_signup_cta_with_examples_loaded` OR `git_signup_cta_without_examples_loaded` depending on Feature Flag value (i.e. Examples Repo component is getting loaded or not).

It also updated the "Continue with GitHub" Clicks analytics, previously we were abusing `Position` ([code ref.](https://github.com/gitpod-io/website/blob/b2a9dfc0f3ad9b05f34a2f2da2912f15ea21f948/src/lib/components/index/get-started/link-git-repository.svelte#L10)). But, Now it would be tied to the same property `experiments_variant` (for consistency & easy to track) with values `git_signup_cta_with_examples_clicked` OR `git_signup_cta_without_examples_clicked` to eventually track the data in Graphs that **_How many times it got loaded vs How many times it got clicked_**.

Aside, This PR also Refactors the Feature Flag service and it's more reliable & Concrete with the feature flag value. 

## Related Issue(s)

Fixes MKWEB-28

## How to test

- Open Website Preview & Segment Staging Debugger.
- Open Homepage on Website. And you will able to see a new event named `component_loaded` in the segment with the property `git_signup_cta_experiment` and having value `git_signup_cta_with_examples_loaded` OR `git_signup_cta_without_examples_loaded`.
-  When you will click on "Continue with GitHub". It would trigger the `website_clicked` event with property `git_signup_cta_experiment` and its value as `git_signup_cta_with_examples_clicked` OR `git_signup_cta_without_examples_clicked`

## Release QA Checklist ✔️

<details>
  <summary>QA Checklist </summary>

## [Priority: High] Functional Testing

- [x] Test all links to make sure they are working correctly
- [x] Verify that all forms (sales, support, docs feedback)  are functioning properly and data is being captured correctly
- [x] Check all buttons and calls-to-action to ensure they are leading to the correct pages
- [x] Ensure that the website is mobile responsive and functions properly on different devices
- [x] Ensure that page is optimal for Light/Dark Mode. ⇒ Text/Media Changes

## [Priority: High] Content Testing

- [ ] Check all website copies for accuracy and spelling/grammar errors
- [ ] Verify that all images and videos are displaying properly
- [ ] Ensure that all downloadable files are working correctly
- [ ] Check that all external links are functioning properly

## [Priority: Medium] Performance Testing

- [ ] Try to use optimal media assets. ([Decision Record - How To](https://github.com/gitpod-io/website/blob/main/docs/adr/0003-optimal-assets-format.md))
- [ ] Test website load times to ensure that the website is loading quickly
- [ ] Verify that the website can handle high traffic volumes without crashing
- [ ] Check that all website functionality is working properly under heavy load
- [ ] Perform cross-browser testing to ensure that the website works properly on all major browsers (Google Chrome, Firefox, Edge)

## [Priority: Medium] Accessibility Testing

- [ ] Ensure that the website meets basic accessibility guidelines.
- [ ] Test that users with disabilities can easily navigate and use the website
- [ ] Verify that all website content can be accessed using assistive technologies

By including these key items in your website release QA checklist, you can ensure that your website is fully functional, user-friendly, and meets your business requirements.

## Security Testing

> **Note**:💡 If we are changing something related to cookies or data storing or analytics side.

- [ ] Verify that the website is HTTPS secure and that there are no security vulnerabilities
- [ ] Ensure that all sensitive data is being stored and transmitted securely

  </details>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3742"></a>

### CODE REVIEW

**Comment by jakobhero** [comment]
introducing `component_loaded` seems reasonable to me and the data model will for us, but i don't understand why we're only providing the experiment context to the git providers on the left and not the example workspaces of the right of the variant with the example workspaces.
it was my understanding that the hypothesis was "too many options are detracting visitors from clicking anything", which naturally also includes the example workspaces (if a user is not signed up, the immediate consequence of clicking on the example is the same as clicking on the `Continue with GitHub` button anyways). if we're not including the buttons on the right in the experiment, it tests instead the hypothesis "is it more likely that a user clicks one of three buttons when three are displayed than one of three buttons when nine are displayed?". the answer to the latter is self-evident and does not require an experiment😅
i suggest to include the `experiments_variant` for the example workspaces too and merge it then

**Comment by Siddhant-K-code** [comment]
Unfortunately, this method doesn't seems to work. Is it really a thing, we wanted to do? (as we only have this specific - one feature flag). We can plan on more better technique if we have any more feature flags in future
Right Now, we have a basic data analytics to track the clicks. But, to get which component is getting loaded is a tedious task with current setup for these components. We can focus on while implementing the feature flag & tieing that to certain component.
For now, Let's keep it this way only. From Next A/B Experiments we will render 2 different component independently (without being dependent to each other) and then we can tie all the analytics. But, for now, we have a good limiting solution, so let's keep it this way as it doesn't seems to high ROI for this much amount of efforts (I have tried to debug this in most of the time today with different-different techniques, but it doesn't seems to work reliably -- there was some mismatch in the data response). I will close the PR for now :pray:

**Comment by Siddhant-K-code** [comment]
We now also have `launch_example_workspace_clicked` as the property value of `experiments_variant` of the Example Workspaces Component (right one).

// cc: @jakobhero

**Comment by Siddhant-K-code** [comment]
@chrifro, @jakobhero We can now compare Property `experiments_variant` in the graph.

- We now have two cases here, as this component loaded in both cases i.e. 
    - **Case A**: Only Git Signup CTA Button component gets loaded -
        -  We would use `git_signup_cta_without_examples_loaded` & `git_signup_cta_without_examples_clicked`
    - **Case B**: Both Git Signup CTA Button & Example Workspace component gets loaded -
        - i) To track Git Signup CTA: we would use `git_signup_cta_with_examples_loaded` & `git_signup_cta_with_examples_clicked`.
        - ii) To track Example Workspace CTAs: we would use `git_signup_cta_with_examples_loaded` & `launch_example_workspace_clicked`


I will leave this up to both of you, What & How do we need to track all this?

**Pull request merged**
