### PR TITLE
[blog] Add Jan 25th outage blog post

### LINKED ISSUE #1559: Publish blog post for Jan 25th incident
Following up on [this incident](https://www.gitpodstatus.com/incidents/tk0f7xcw8q94), we plan to author a blog post.

The blog post is drafted, remaining tasks are to:

1. Finalize the closing
2. Review with the DCS team

The draft post is [located here](https://www.notion.so/gitpod/January-25th-Gitpod-Outage-359bcce1e17b4774ad7533b443735401).

### PR DESCRIPTION
**Pull request by kylos101**
## Description

Jan 25th outage blog post

- [x] add a teaser.png to `static/images/blog/no-way-it-is-dns` using [Figma](https://www.figma.com/)

## Related Issue(s)

Fixes #1559

## How to test

n/a

## Release Notes

```release-note
```

## Documentation

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/1564"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1564"></a>

### CODE REVIEW

**Comment by kylos101** [comment]
cc: @sagor999

**Comment by kylos101** [comment]
@ChristinFrohne @gtsiolis hello there, @mikenikles pointed me in your direction. May I ask for help? :pray: 

We require a `teaser.png` file for the blog post in this PR...can you help create one? 

Alternatively, if we have an existing library of prior art, I'd be happy to pull from it. But I would need to know if there's a color scheme or pattern we're trying to follow with the teaser background color.

**Comment by gtsiolis** [comment]
@kylos101 checkout the existing 3D illustrations available in this Figma file linked from this section[[1](https://www.notion.so/gitpod/Blogging-34c2e078569b4174b42784854f42549f#217feeb4f935408390cd7cefd7377f71)] in our blogging guidelines. Happy to help if needed. Cc @ChristinFrohne

**Comment by ChristinFrohne** [comment]
@kylos101 the blog post image you choose is meant for DevX Digests only, as the dotted image is another style. I will try to make that clearer in the Figma file 🙂

What do you think about any of these images instead?
Blog Post Workspace Networking - header (1)

Blog Post Workspace Networking - header (2)

**Comment by kylos101** [comment]
Hey @ChristinFrohne thanks for the heads up! I opted for this second one that you shared. :pray:

**Pull request merged**
