### PR TITLE
[docs] Use official Servo repository in Rust guide (instead of my personal fork)

### PR DESCRIPTION
**Pull request by jankeromnes**
The Gitpod config I try to maintain for https://github.com/servo/servo lives in https://github.com/gitpod-io/definitely-gp/tree/master/servo

### CODE REVIEW

**Comment by jankeromnes** [comment]
My personal fork may lag behind, and also I often use it for experiments / to test things that may break.

**Comment by jankeromnes** [comment]
> (https://gitpod.io/#https://https://github.com/servo/servo)
> You use https:// twice

Oops, good catch! Thanks.

> Also does the servo repo have a gitpod config?

see https://github.com/gitpod-io/website/pull/471#issue-372012675 😇

**Comment by JesterOrNot** [comment]
image
But there is no config there and the open in gitpod button redirects to
https://github.com/servo/servo

**Comment by jankeromnes** [comment]
Gitpod supports external configurations via this repository: https://github.com/gitpod-io/definitely-gp

If you click on second link in:

Screenshot 2020-02-06 at 19 17 18

You'll find the `.gitpod.yml` and `.gitpod.dockerfile` I maintain for Servo:

Screenshot 2020-02-06 at 19 19 19

**Comment by jankeromnes** [comment]
> You use https:// twice

Fixed. ✔️

**Comment by JesterOrNot** [comment]
Can we merge this?

**Comment by jankeromnes** [comment]
> Can we merge this?

Sure! No need to ask. 😄

If, as a reviewer, you're happy with the contribution and think it's an improvement, please feel free to merge it after you've reviewed it.

Or, if you're not sure whether this was ready yet, you can leave it approved, and wait for the developer to merge it (but only if they have write access).

**Comment by JesterOrNot** [comment]
Ok, Great Thanks!

**Pull request merged**
