### PR TITLE
Introduce `manage cluster nodes` as Troubleshooting material

### PR DESCRIPTION
**Pull request by kylos101**
## Description

Some customers have asked how to prevent the autoscaler from removing nodes that are unhealthy, where they might want to do a manual user data backup.

## Related Issue(s)

Related to: https://github.com/gitpod-io/website/issues/2721

## How to test

n/a

## Release Notes

```release-note
Introduce manage cluster nodes doc for troubleshooting material
```

## Documentation

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2772"></a>

### CODE REVIEW

**Review by aledbf — APPROVED** [review]

**Review by lucasvaltl — APPROVED** [review]
LGTM :)

**Comment by kylos101** [comment]
:wave: @mrzarquon , if you don't have any objections, may I ask for your approval and to merge?

**Comment by kylos101** [comment]
@mrzarquon hey there, merged to squeeze in before the docs freeze. If you'd like any changes, let's handle in a follow-up?

**Comment by mrzarquon** [comment]
> @mrzarquon hey there, merged to squeeze in before the docs freeze. If you'd like any changes, let's handle in a follow-up?

✅

**Review by mrzarquon — COMMENTED** [review]
✅

**Pull request merged**
