### PR TITLE
add missing alt texts.

### PR DESCRIPTION
**Pull request by nisarhassan12**
image

Addresses part of #821

### CODE REVIEW

**Comment by nisarhassan12** [comment]
@ChristinFrohne In the issue comment, you said there are 5 missing alt texts so far I have only been able to find 2 (one on the home page and the other on the gitpod vs codespaces page). How did you find the rest of them i.e did you manually audit all the pages ?

**Comment by ChristinFrohne** [comment]
The SEO checker provided this information for the missing alt-tag:
1. 
/static/collaboration-placeholder-079eda3cb3f89e03df607ef9f8eb2b8d.png

2.
data:image/svg+xml;base64,phn2zyb4bwxucz0iahr0cdovl3d3dy53my5vcmcvmjawmc9zdmciihdpzhropsixms44otuiighlawdodd0imteuodk1iib2awv3qm94psiwidagmteuodk1idexljg5nsi+pgcgawq9ikdydxbwzv85njeiigrhdgetbmftzt0ir3j1chblidk2msigdhjhbnnmb3jtpsj0cmfuc2xhdguoltezmdgundi5ic01odu5ljy3nykipjxsaw5liglkpsjmaw5pzv8xodiiihkypsixmi44mjeiigzpbgw9im5vbmuiihn0cm9rzt0ii2jjymniyyigc3ryb2tllwxpbmvjyxa9injvdw5kiibzdhjva2utd2lkdgg9ijiiigrhdgetbmftzt0itgluawugmtgyiib0cmfuc2zvcm09inryyw5zbgf0zsgxmze4ljkwosa1odyxlja5mskgcm90yxrlkdq1ksivpjxsaw5liglkpsjmaw5pzv8xodmiihgxpsixmi44mjeiigzpbgw9im5vbmuiihn0cm9rzt0ii2jjymniyyigc3ryb2tllwxpbmvjyxa9injvdw5kiibzdhjva2utd2lkdgg9ijiiigrhdgetbmftzt0itgluawugmtgziib0cmfuc2zvcm09inryyw5zbgf0zsgxmza5ljg0mya1odyxlja5mskgcm90yxrlkdq1ksivpjwvzz48l3n2zz4=

3. data:image/svg+xml;base64,phn2zyb4bwxucz0iahr0cdovl3d3dy53my5vcmcvmjawmc9zdmciihdpzhropsixocigagvpz2h0psixocigdmlld0jved0imcawide4ide4ij48zybpzd0ir3j1chblxzk2miigzgf0ys1uyw1lpsjhcnvwcgugotyyiib0cmfuc2zvcm09inryyw5zbgf0zsgtmtm0ns41ic01odu2ljupij48bgluzsbpzd0itgluawvfmtgwiib5mj0imtyiigzpbgw9im5vbmuiihn0cm9rzt0ii2jjymniyyigc3ryb2tllwxpbmvjyxa9injvdw5kiibzdhjva2utd2lkdgg9ijiiigrhdgetbmftzt0itgluawugmtgwiib0cmfuc2zvcm09inryyw5zbgf0zsgxmzu0ljugntg1ny41ksivpjxsaw5liglkpsjmaw5pzv8xodeiihgxpsixniigzmlsbd0ibm9uzsigc3ryb2tlpsijymniy2jjiibzdhjva2utbgluzwnhcd0icm91bmqiihn0cm9rzs13awr0ad0imiigzgf0ys1uyw1lpsjmaw5pzsaxodeiihryyw5zzm9ybt0idhjhbnnsyxrlkdezndyunsa1ody1ljupii8+pc9npjwvc3znpg==

4. data:image/svg+xml;base64,phn2zyb4bwxucz0iahr0cdovl3d3dy53my5vcmcvmjawmc9zdmciihdpzhropsi1mtiiighlawdodd0inteyiibmawxspsijrjdgn0y3iib2awv3qm94psiwidagnteyiduxmii+phrpdgxlpmlvbmljb25zlxy1lws8l3rpdgxlpjxwyxroigq9ik0ynjcsndc0bc0uoc0umtnbljg1ljg1ldasmcwwldi2nyw0nzraii8+phbhdgggzd0ittq0oc45lde4ny43oge1ljuxlduuntesmcwwldatmtaunjctljyzadbbns41miw1ljuyldasmcwxldqzmywxotfinde3ljuzytuundgsns40ocwwldasms0yljg0ls43owwtmjiumzgtmtmundjhns40ocw1ljq4ldasmcwwltiuodqtljc5ac0zns44ytuundgsns40ocwwldasmc0zlja2ljkzbc00nc4xnswyos40m0e1ljuylduuntismcwwldasmza0ldixmxy0ms43nge1ljuxlduuntesmcwwldasmi45miw0ljg3bdu3ljg5ldmwljlhns41nsw1lju1ldasmcwxldiuotisnc44tdm2ocwzmtyuoge1ljuzlduuntmsmcwwldasmi44nsw0ljc1bdizlji2ldeyljg3ytuuntqsns41ncwwldasmswyljg1ldquodn2ndgunme1ljuylduuntismcwwldasos4xnyw0lje0yzkumzgtoc4yniwymi44my0ymc4zmiwync42mi0ymy4wohe0ljq0ltyuodcsoc4zmy0xnc4wn2eymdcumzksmja3ljm5ldasmcwwldezljytmzfdndy1ljm2ldi4ny4xmyw0ntuumzqsmjixlje0ldq0oc45lde4ny43ofoilz48cgf0acbkpsjnmjg2ljqsmzayljhsltyxljmzltq2ytqsncwwldasmc0yljqtljholti5ljfhmy43ocwzljc4ldasmcwxltiunjgtms4xmwwtmtmunzitmtmunzjhncw0ldasmcwwltiuodmtms4xn0gxmjeumtvhmy43oswzljc5ldasmcwxltiunjgtni40n2w4ljqyltgundjhmy43ocwzljc4ldasmcwxldiunjgtms4xmwgzmi4zn2e4ldgsmcwwldasny43ltuuodnsni44os0ync41ytqsncwwldasmswyltiunddmmja2lde3ny4wnmezljc5ldmunzksmcwwldasmi4wns0zljm3di0xmi41ytmuodismy44miwwldasmswunjgtmi4xn0wymjmumzmsmtm4ytmunzusmy43nswwldasmswxljc4lteumzhsmjaundmtny42n2ezljc5ldmunzksmcwwldasmi40ni0zlju1vjexngezljgsmy44ldasmcwwlteunjktmy4xnkwymjuuodmsotcumjjbmy44mywzljgzldasmcwwldiymiw5n2wtmjcuodgsmtmuotrhmy43ocwzljc4ldasmcwxltqtljqxtde3ni45ldewmc4wogezljgsmy44ldasmcwxlc4xltzsmtaunzqtny45mwezljc4ldmunzgsmcwwldatlja5ltyumtzmmtcwljkyldy4ljm0ytmunzgsmy43ocwwldasmc00ls4ymmmtni4wnswzljmxltizljgsmtmumtetmzaumswxny41mmeymdkundgsmja5ljq4ldasmcwwlty4lje2ldgwyy0xljgyldmunzytnc4wnyw3lju5ltqumjksmteunzjzltmundysmtmumzutnc44mswxny4wogezljc4ldmunzgsmcwwldaslji0ldmumwwzns42osw2ns41ogezljc0ldmunzqsmcwwldasms4zocwxljq0bdm3lju1ldiylju0ytmunzgsmy43ocwwldasmswxljgxldiunznsny41miw1nc41ngezljgyldmuodismcwwldasms42mswyljyxbdi5ljmsmjaumtrhncw0ldasmcwxldeunjusmi40ogwxns41ncw3my44ytmuniwzljysmcwwldasljq5ldeumjjjms40niwyljm2ldcumjgsmtesmtqumywxmi4yoc0unjuumtgtms4ymy41os0xljg4ljc4ytq3ljyzldq3ljyzldasmcwxldusms4xnmmylc41ncw0ldesniwxljqzldmumtmunjismy40ncwxljesnc45nc0xljy4lditmy43miw0lji5ltusni01ljq2ytmuodusmy44nswwldasmcwyljg5ltiuowwxmc4wny00ni42oge0ldqsmcwwldesms42ltiundjsndutmzeuowe0ldqsmcwwldasms42os0zlji3vjmwnke0ldqsmcwwldasmjg2ljqsmzayljhaii8+phbhdgggzd0itti2miw0ohmtmy42ns4yms00ljm5ljizcs04ljezlji0lte2ljiyldeumtjbmja3ljq1ldiwny40nswwldasmcwxodqumjesnjrjmi40mywxljy4lteunzusmy4ymi0xljc1ldmumjjmmtg5ldgwadm1bdi0ldeyldixlteywiivpjxwyxroigq9ik0zntqumjmsmtiwlja2bde2ljexlte0ytqsncwwldasmc0uotqtni42nwwtmtguodetoc43m2e0ldqsmcwwldatns4zldeuowwtny43nswxni4ymwe0ldqsmcwwldasms40osw1ljexbdewljq2ldyuntrbncw0ldasmcwwldm1nc4ymywxmjaumdzaii8+phbhdgggzd0ittqyos42ncwxndaunjdsltuuodmtowmtlja5ls4xnc0umtctlji4ls4yns0undmtms4wns0ylje1ltkunzqtmtkuny0xny0yni41ms01ljq1ltuumtutny0zljy3ltcundmtmi41m2ezljc3ldmunzcsmcwwldetms4xoswxljzmmzy5ljesmti3ljexytqsncwwldasms0yljuxljg5sdm1ms42nme0ldqsmcwwldatmi44mywxlje3bc0xmiwxmme0ldqsmcwwldasmcw1ljy2bdeyldeyytqsncwwldasmcwyljgzldeumtdonzuumtdhncw0ldasmcwwldqtnc4xn2wtlju1ltezlje1qtqsncwwldasmcw0mjkunjqsmtqwljy3wiivpjxwyxroigq9ik0yntysnzjhmtg0lde4ncwwldesms0xmzaumsw1my45qte4mi43nywxodiunzcsmcwwldesmju2ldcybtatndbdmtmyljmsmzismzismtmyljmsmzismju2uzezmi4zldq4mcwyntysndgwldq4mcwznzkunyw0odasmju2ldm3os43ldmyldi1niwzmloilz48l3n2zz4=

Does that help? @nisarhassan12

**Comment by nisarhassan12** [comment]
Thanks. @ChristinFrohne This doesn't help. I was trying to convert these base 64 images to png so that I can view and identify them. Not sure how we can view the base64 format I tried pasting these string into the browser but they don't seem to be working.

image

**Comment by ChristinFrohne** [comment]
I also couldn't find a way to decode the base64 format. Let's just merge the fixes for the other alt-tags now and then see if the error message still exists. If so, we can address them in a separate issue.

**Pull request merged**
