### PR TITLE
doc: add self-hosted on tencent cloud guide

### PR DESCRIPTION
**Pull request by yaohui-wyh**
## Description

Publish the guide on self-hosting Gitpod on Tencent Cloud ([Notion page](https://spurious-amount-763.notion.site/Gitpod-Self-hosted-installation-on-Tencent-Cloud-b1374ef5783d4d8a9784aae85859d6ee))

Thank @akosyakov @iQQBot for the help & guidance.

## Related Issue(s)

Fixes #

## How to test

Preview the document from a Gitpod workspace:

[Open in Gitpod](https://gitpod.io/#https://github.com/gitpod-io/website/pull/2233)

## Release Notes

```release-note
Add self-hosted installation guide on Tencent Cloud.
```

## Documentation

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2233"></a>

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
Thank you for the contribution 🚀, I accepted the deployment preview, so you get a preview environment for the PR.

**Comment by csweichel** [comment]
/hold

internal discussion: https://gitpod.slack.com/archives/C01LDA27WJC/p1655193805007819

**Comment by ghuntley** [comment]
Hey @yaohui-wyh,

We would like to feature your guide but as per https://www.gitpod.io/docs/contribute/content could you please publish the instructions on your channel/website, add the link to [awesome-gitpod](https://github.com/shaal/awesome-gitpod) and then let us know the link? By posting content first on your own site/channel then a direct feedback cycle forms between you and your readership through ownership of your content that helps you to improve your content.

ps. If Tencent wish to partner with Gitpod in an official capacity then please get in contact via https://www.gitpod.io/contact

**Comment by yaohui-wyh** [comment]
Hi @ghuntley, thanks for the reply! Sorry for not reading through the [Contribute Content](https://www.gitpod.io/docs/contribute/content) at first and raising PR without prior discussion. I will close the PR. 🙏

**Pull request closed without merging**
