### PR TITLE
switch sections "TrustedBy" with "Testiomonials" + add more tweets.

### LINKED ISSUE #450: Switch TrustedBy and twitter quotes sections.
I think the quotes are much better than the logos (also because they are not really popular ones).
And it makes the whole thing more personal.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #450 
This is how it looks like:

image

### CODE REVIEW

**Comment by svenefftinge** [comment]
The last tweets includes the previous one so the previous one should be removed.
Would it be possible to have an infinite scrolling that circles around and start with ben's tweet?

**Comment by nisarhassan12** [comment]
> The last tweets includes the previous one so the previous one should be removed.
> Would it be possible to have an infinite scrolling that circles around and start with ben's tweet?

Not sure, but I can look into this.

**Comment by nisarhassan12** [comment]
> Would it be possible to have an infinite scrolling that circles around and start with ben's tweet?
I tried implementing it but I'm not able to do so.

**Comment by svenefftinge** [comment]
thanks!

**Pull request merged**
