### PR TITLE
add announcement banner that we are hiring.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes gitpod-io/website#967

This is how it looks: 

image

### CODE REVIEW

**Comment by JohannesLandgraf** [comment]
Thanks @nisarhassan12! Seems to work well. However it is way too invasive and prominent. The banner should probably be at most half the size and the font size also respectively smaller. There is also no need to use bold font here. To be a bit more colloquial I would change the text to: "We're hiring".

**Comment by nisarhassan12** [comment]
I have made the requested changes.

**Comment by JohannesLandgraf** [comment]
Thanks @nisarhassan12! 

- The button to close the banner is not visible anymore
- We should resize the opening hover button. `font-size`:1.4rem / `margin-left`: 1.5rem /
- Change the text to "We're hiring!"

Such as:
Screenshot 2021-01-27 at 18 34 06
 
 Maybe even decrease the banner height even more (but up to you to decide what still looks good) :)

**Review by JohannesLandgraf — APPROVED** [review]
Once you fix the things in my comment above feel free to merge on your own 🙏

**Pull request merged**
