### PR TITLE
:sparkles: new `/resources` page

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
fixes MKWEB-67

Preview on: [`/resources`](https://deploy-preview-3792--gitpod-kumquat.netlify.app/resources)

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3792"></a>

### CODE REVIEW

**Review by chrifro — COMMENTED** [review]
- according to this issue, only 1/3 of issues have been addressed in this PR. Isn't it a minor visual change that can be included directly in this PR? [[1](https://linear.app/gitpod/issue/MKWEB-66/align-support-page-styles)]. 
- let's use consistently lowercase spelling e.g. "Get started". Only proper names came with a capital letter e.g. Discord
- did you check it for smaller screen sizes? The cards should have a consistent width 
Bildschirmfoto 2023-06-27 um 11 56 37

**Comment by Siddhant-K-code** [comment]
> according to this issue, only 1/3 of issues have been addressed in this PR. Isn't it a minor visual change that can be included directly in this PR? [[1](https://linear.app/gitpod/issue/MKWEB-66/align-support-page-styles)].

Sorry, if there is any confusion. This PR is to solve [MKWEB-67 : Create `/resources` page to list out Helpful resources](https://linear.app/gitpod/issue/MKWEB-67/create-resources-page-to-list-out-helpful-resources) & **not** [MKWEB-66 : Align `/support` page styles](https://linear.app/gitpod/issue/MKWEB-66/align-support-page-styles)

> let's use consistently lowercase spelling e.g. "Get started". Only proper names came with a capital letter e.g. Discord
>
> did you check it for smaller screen sizes? The cards should have a consistent width

will do that in the next commit. Thanks for the review 🧡

**Comment by Siddhant-K-code** [comment]
There seems to be a bug 🐛 across the website (common component). Fixed now ✅ 



https://github.com/gitpod-io/website/assets/55068936/74c68a2f-4c5e-4d2c-ac18-721a29bfefa7

**Review by meysholdt — APPROVED** [review]
This looks great! Thank you, @Siddhant-K-code

**Comment by Siddhant-K-code** [comment]
> Nit: It would be nice to add:
>
> a like to the support page
> a link to "samples" aka "templates".

fixed in [**`0c833bc`**](https://github.com/gitpod-io/website/pull/3792/commits/0c833bc14246e142d60c7331b4cdb7a57f290d3f)

**Pull request merged**
