### PR TITLE
update hero image [merge date: feb 24]

### LINKED ISSUE #1571: Update workspace cube image
workspace-jetbrains-new-arrangement

### PR DESCRIPTION
**Pull request by chrifro**
fixes #1571

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/1578"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1578"></a>

### CODE REVIEW

**Comment by ChristinFrohne** [comment]
Thanks for the great description in #1571 @nisarhassan12 🙏 I tried, but could you take this over and adjust the image size and add a shadow style to the image? For details [see mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=1559%3A175)
Thank you!

**Comment by nisarhassan12** [comment]
@ChristinFrohne Done. Please have a look at the Pr when you get time. Thanks.

**Comment by ChristinFrohne** [comment]
Updated image
workspace-jetbrains (1)

**Comment by nisarhassan12** [comment]
Closing this as the Cube is gonna be updated.

**Pull request closed without merging**
