### PR TITLE
improve the faq animation.

### LINKED ISSUE #1539: Changelog - January 28, 2022

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #1539 

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/1827"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1827"></a>

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
Just a question, couldn't we use the[ svelte build-in transitions ](https://svelte.dev/docs#run-time-svelte-transition)for this

**Comment by nisarhassan12** [comment]
> Just a question, couldn't we use the[ svelte build-in transitions ](https://svelte.dev/docs#run-time-svelte-transition)for this

Thanks, @Cahllagerfeld 👍🏿  for bringing this up. Looking at the component code I don't think it is feasible to use built-in ones i.e the animation is not just an element being added or removed to the DOM. In case you have ideas on How to use the Svelte built-in transitions for this particular animation then do let me know. Thanks

**Comment by nisarhassan12** [comment]
@chrifro This is still a draft and there is an issue to fix here but I would like to know what do you think of the updates so far? Any feedback? Thanks

**Comment by nisarhassan12** [comment]
>  Could you just focus on the text not being cut when closing the FAQ?

@chrifro Done.

**Comment by nisarhassan12** [comment]
@chrifro I'm merging this let me know in case you have any other feedback I'll follow up on that.

**Pull request merged**
