### PR TITLE
fix: migrate gitpodify guide to guides from blogs

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

Migrated Gitpodify Ultimate guide to guides section from blogs.

## Test

- Open [Preview URL](https://deploy-preview-2704--gitpod-kumquat.netlify.app/guides/gitpodify) 
- Test [Redirect URL](https://deploy-preview-2704--gitpod-kumquat.netlify.app/blog/gitpodify) 

> Signed-off-by: Siddhant Khare <siddhant@gitpod.io>

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2704"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2704"></a>

### CODE REVIEW

**Comment by JohannesLandgraf** [comment]
That went well. Can't do a deep code review but couple of things we should consider: 

- Impact on SEO as the blog post had a high click rate

Maybe we just create a preview under /guides and then link to the existing blog post? Would solve the problem.

**Comment by Siddhant-K-code** [comment]
> Maybe we just create a preview under /guides and then link to the existing blog post? Would solve the problem.

Will take a look on this 🤔

**Comment by Siddhant-K-code** [comment]
@JohannesLandgraf I don't think, it would affect SEO.
Because all traffic that would be coming to `/blog/gitpodify` will be redirected to `guides/gitpodify`

Test [`Preview-URL/blog/gitpodify`](https://deploy-preview-2704--gitpod-kumquat.netlify.app/blog/gitpodify) -> Will be redirected to `/guides/gitpodify`

**Review by Cahllagerfeld — COMMENTED** [review]
I think we should add a different Thumbnail that aligns with the other guides as well 🤔. Do you have any suggestions @chrifro, or shall I come up with a proposal?

**Comment by chrifro** [comment]
>Do you have any suggestions @chrifro, or shall I come up with a proposal?

Mh what about  "Gitpod" ... "any project" for the header? (see[ Figma](https://www.figma.com/file/gq1v6dj0rzs4tvJcFabKPy/Blog-%26-Changelog-images?node-id=1331%3A831)) WDYT @Cahllagerfeld ?

As discussed in the website sync, after the "gitpodify" blog post content has been updated, we pin it to the top of the list to increase visibility.

**Comment by Siddhant-K-code** [comment]
I think, regarding content & header changes. We can do that in a follow-up PR (as we discussed in website-sync)

cc: @chrifro @Cahllagerfeld

**Review by Cahllagerfeld — APPROVED** [review]
From the techincal point it looks good to me 👍 
Regarding the image it's on @chrifro I think 😅

**Comment by chrifro** [comment]
Let's just swap the image directly in this PR. I already added the design in Figma (see [here](https://www.figma.com/file/gq1v6dj0rzs4tvJcFabKPy/Blog-%26-Changelog-images?node-id=1331%3A909))
Bildschirmfoto 2022-09-12 um 16 02 32

**Pull request merged**
