### PR TITLE
Create previous changelog entries

### LINKED ISSUE #1501: Create previous changelog entries
2021 was a busy year, but the changelog doesn't fully reflect that.

### PR DESCRIPTION
**Pull request by mikenikles**
Close #1501.

Requires images for the following entries:
| Done | Preview | File path | Header image ideas |
|---|---|---|---|
| ❌ | [Link](https://deploy-preview-1502--gitpod-kumquat.netlify.app/changelog/automatic-preview-page-reloads) | `static/images/changelog/2021-10-01.jpg` | Something along the lines of the following screenshot to indicate it auto-reloads until the website is ready to load.   |
| ❌ | [Link](https://deploy-preview-1502--gitpod-kumquat.netlify.app/changelog/tailscale-on-gitpod) | `static/images/changelog/2021-10-29.jpg` | The Tailscale logo, a 🤝 emoji, the Gitpod logo |
| ❌ | [Link](https://deploy-preview-1502--gitpod-kumquat.netlify.app/changelog/improved-workspace-startup-times) | `static/images/changelog/2021-11-12.jpg` | I can't think of anything meaningful. |
| ❌ | [Link](https://deploy-preview-1502--gitpod-kumquat.netlify.app/changelog/gitpod-self-hosted-installers) | `static/images/changelog/2021-11-26.jpg` | I can't think of anything meaningful. |
| ❌ | [Link](https://deploy-preview-1502--gitpod-kumquat.netlify.app/changelog/self-managed-k3s-on-gcp) | `static/images/changelog/2021-12-24.jpg` | I can't think of anything meaningful. |

@ChristinFrohne could you create header images for the above changelog entries please?

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/1502"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1502"></a>

### CODE REVIEW

**Comment by ChristinFrohne** [comment]
@mikenikles It would be super helpful if you could add a rough idea of what you imagine to be on the image or add a link that can be used for a screenshot

**Comment by mikenikles** [comment]
The three last ones are very technical and I can't think of an image to represent these changes. @gtsiolis do you have any creative ideas what would be a good image for these changes?

**Comment by gtsiolis** [comment]
@mikenikles I just found this ping[[1](https://github.com/gitpod-io/website/pull/1502#issuecomment-1034388699)] that slipped between the cracks.

Is this PR still relevant? If yes, I think it's ok resist the urge to add a header image on every changelog entry and skip the header image when it does not make sense to add one. 💭

**Comment by Cahllagerfeld** [comment]
Hey @chrifro, when exporting one image, I "just" get the background, but not the computer icon itself. The affected one is the [Self-Hosted Installer one](https://www.figma.com/file/gq1v6dj0rzs4tvJcFabKPy/Blog-%26-Changelog-images?node-id=883%3A494).

**Pull request merged**
