### PR TITLE
Newsletter Component

### LINKED ISSUE #3254: Add newsletter sign-up to homepage
Issue has been created based on [this internal task](https://www.notion.so/gitpod/Create-newsletter-sign-up-component-2f2d44e5f47e4654a2a37d00abf5b963?d=f9f5360ea2464df39744fa8632e724f1#c5712530e4b04c70a9c84ef11b176df8)

Task:
- Create component for newsletter sign-up to be placed at the bottom of the homepage (below the browser extension card)

See [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5186%3A6736&t=P2cHBWn1B4bFku9n-1)
Bildschirm­foto 2023-01-17 um 09 33 15

**Next steps:**
- review messaging @MichaelAring 
- define the link for the button e.g. /notifications @MichaelAring 
    - or should the component include a form to enter the email address and forward them to a Google sheet? 
- technical implementation

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #3254

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3259"></a>

### CODE REVIEW

**Review by Cahllagerfeld — COMMENTED** [review]
Two details here @chrifro: 
- The spacing between the text and the form might be a bit off to the mockup, the reason is that I implemented it the way, we don't have a layout-shift, if the success message updates and gets displayed
- I can remember @securitymirco  telling me that when having such a kind of signup we ideally include a link to the Privacy Policy in the Checkbox, so that's also a bit off from the mockup.

I added the Segment-Thing from another form, but didn't receive a final approval from @jakobhero just yet, if this is working fine in our use case

Let me know if we need further adjustments 👍

**Comment by chrifro** [comment]
Nice ✨

- after one submits their email address. Can you hide the email sign-up field? See [mockup ](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=8777%3A18005&t=me2ZZxRNOhy1HKh8-1)

Bildschirm­foto 2023-01-17 um 16 10 58

- we should display an error message for duplicate email addresses instead of just disabling the CTA. This is difficult to realize from a user perspective. 
Can you use this design and update the text to "This email address is already signed up"?
Bildschirm­foto 2023-01-17 um 16 13 09

- on mobile: can you align the headline with the form? The spacing to the left is inconsistent

Bildschirm­foto 2023-01-17 um 16 17 57

**Comment by chrifro** [comment]
@MichaelAring can you review the messaging? 🙏

**Comment by Cahllagerfeld** [comment]
The message below Newsletter-Signup changes to a third option if the address already exists. Maybe that's not clear enough?

**Review by Cahllagerfeld — COMMENTED** [review]
- updated segment based on Jakobs comment
- adjusted alignment on mobile
- hide input after submission

**Comment by MichaelAring** [comment]
> @MichaelAring can you review the messaging? 🙏

My suggestion
**Learn more about Gitpod**
Our latest thinking, news, and insights into CDEs

Also, the button should say [Subscribe]

**Comment by securitymirco** [comment]
Thank you for adding a reference to our privacy policy, as you pointed out this is important for any form where we expect users to provide personal information to us. 🙏

**Pull request merged**
