### PR TITLE
Add Security Log

### LINKED ISSUE #1692: New Security Blog
In Order to keep track of security-incidents and being transparent with them @MircoatGitpod came up with the idea of creating a blog-style page where we can publish these.

In a call with Mirco and @ChristinFrohne we decided to kind of reuse the existing `Changelog`-Layout for this.

The Idea is to provide a page at `/security/blog` or `/security/log` where we can put it `markdown`-files and publish them, as mentioned earlier in the Changelog-Style.

Do we need a dedicated Page for every Changelog, or is the Timeline-View we are having at `/changelog` currently enough?

Any additional features, like subscribing to it for example, can come in future PRs.

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #1692

- [x] Init Changelog-Style
- [x] Add Link from `/security` to `/security/log`
- [x] polish Layout of `/security`

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/1694"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1694"></a>

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
For some reason the TOC of the blogpost regarding used `h-`Elements gets displayed at the end of every blogpost. I couldn't find the spot where this happens, or is it auto-generated with the `rehype-plugin` @mikenikles?

**Comment by Cahllagerfeld** [comment]
Preview can be found [here](https://deploy-preview-1694--gitpod-kumquat.netlify.app/security/log)

- [x] Init Changelog-Style
- [ ] Add Link from `/security` to `/security/log`

**Review by ChristinFrohne — COMMENTED** [review]
Nice, thanks! ✨

A few comments:

**on /security:**

- [x] change CTA to "View security program" linking to the section on the same page (see mockup)

- [x] the spacing in the cards seems off. Could you make sure that we use a consistent style. See [component library](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A2831). The style is also used on www.gitpod.io

**Security log**

- [x] add an explaining sub header e.g. "A sum-up of Gitpod’s latest security findings and updates."

- [x] could you reduce the spacing between the headline section and the first entry?

- [x] add a bit more spacing to the bottom of the page 
Bildschirmfoto 2022-03-03 um 10 56 43

After you address the comments above, the PR good to go from my side. Could you ping Mirco to review the messaging as well before merging it? Thanks :)

**Comment by ChristinFrohne** [comment]
The style of the cards is still off @Cahllagerfeld 
|on gitpod.io | on /security|
|-|-|
|Bildschirmfoto 2022-03-03 um 16 12 03|Bildschirmfoto 2022-03-03 um 16 11 50

**Pull request merged**
