### PR TITLE
[docs] small fixes for mobile.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #448

### CODE REVIEW

**Comment by jankeromnes** [comment]
@JesterOrNot Could you please take a look at this Pull Request when you have time?

I think @nisarhassan12's improvements make your language guides more readable on mobile. Feel free to use a mobile device, or your browser devtools' mobile emulator, in order to compare the docs layout between the current website and the Netlify preview here.

**Comment by nisarhassan12** [comment]
> The new CSS has it go off the page
> image
> image

Hey! Sean Many Thanks for the review! :slightly_smiling_face:  It's is actually not because of the new CSS and it's already being fixed in https://github.com/gitpod-io/website/pull/446. This branch is behind origin master that's why you still see the problem. If you were to take a look at https://www.gitpod.io/docs/python-in-gitpod/ you'll see it's all right.

**Comment by nisarhassan12** [comment]
> Looking at the preview the CSS seems outright broken
> image
> But except for that looks great! Thanks

Weird this does not happen on my end. And also I have not touched a single bit of CSS for this part of the site.

**Comment by JesterOrNot** [comment]
https://www.loom.com/share/10432eb0b29c4953bfe307f0890a486f

**Comment by nisarhassan12** [comment]
> https://www.loom.com/share/10432eb0b29c4953bfe307f0890a486f

Please try reloading it by disabling the cache ?

**Comment by nisarhassan12** [comment]
> Please try reloading it by disabling the cache ?

Maybe try opening a workspace with this PR and then have a look the preview site looks fine on my end: 
image

**Pull request merged**
