### PR TITLE
[docs] Automate /release-notes/all.json build

### PR DESCRIPTION
**Pull request by jankeromnes**
Fixes https://github.com/gitpod-io/gitpod/issues/714

### CODE REVIEW

**Comment by jankeromnes** [comment]
... but I think this change might suddenly show the June release notes to many people.

Maybe let's merge this when we publish new release notes (e.g. in August).

**Comment by svenefftinge** [comment]
The images are not shown properly, which is why I disabled the release notes.

**Comment by jankeromnes** [comment]
> The images are not shown properly, which is why I disabled the release notes.

Thanks for the explanation. When we publish the next Release Notes, I'd like to try and fix image display, and then re-publish the June notes.

**Comment by jankeromnes** [comment]
We have https://www.gitpod.io/docs/changelog/ now.

**Pull request closed without merging**
