### PR TITLE
adjust layout for tablet size devices.

### LINKED ISSUE #803: [gitpod-vs-gh-codespaces]: needs layout adjustments for tablet devices.
image

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #803

| Before | After |
| - | - |
| image | image |

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/808"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/808"></a>

### CODE REVIEW

**Review by ChristinFrohne — COMMENTED** [review]
Great fix, it looks much better now!

Is there any way we can make the footnotes less present? Would it pass the accessibility test if we either reduce the size or use the lighter grey?
If not, could you add a bit more space between the headlines and the footnotes? 
Bildschirmfoto 2021-08-03 um 10 16 48

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have added more spacing below the footnote. Please approve if the change looks good to you. Making it smaller while using a grey colour would result in accessibility issues.

**Comment by ChristinFrohne** [comment]
>Making it smaller while using a grey colour would result in accessibility issues.

I was wondering if one of the changes (either changing the color **or** the font size) would be possible. 
If that would result in accessibility issues, we can merge the PR as it is now.

**Comment by nisarhassan12** [comment]
Thanks @ChristinFrohne using the `light-grey` colour will have accessibility issues. Currently the font size for the footnote is `12px` using a smaller font size is not recommended.
image

**Pull request merged**
