### PR TITLE
Sections to feature table

### LINKED ISSUE #2160: Sections for Pricing Page Feature List.
This is not a Must for Q2 2022. But if we have capacity, this would be good to do soon. 

### Describe your feature

In order to better organise our feature list on the pricing page(s), we should have sections that allow us to group features by topic - see examples from [vercel](https://vercel.com/pricing) and [curity](https://curity.io/product/plans/). This means adding the ability to have these sections, and then defining which feature should be in which section. 

### How to test

When navigating to the pricing page, I can see clear groupings of features.

This likely would first need a design proposal @chrifro.

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #2160

hover styles are tackled in #1416 

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2384"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2384"></a>

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
Hey @lucasvaltl, I've made the changes to the feature table and implemented them in an example [here](https://deploy-preview-2384--gitpod-kumquat.netlify.app/self-hosted#view-all-features). I think it's ready for you to adjust the relevant content, edit headlines, etc... Let me know if you need support with that, I'm glad to help

**Comment by mikenikles** [comment]
@lucasvaltl Do you want to make content changes as part of this PR or as a follow-up?

**Comment by lucasvaltl** [comment]
Hey @mikenikles - thanks for checking in. This has been part of my to do list for a while. I'll likely get around to it by the end of this week. If I fail to do so, let|s merge this and do the content changes as a follow up :)

**Comment by lucasvaltl** [comment]
On second thought, I'd like to propose content changes that would likely create discussions outside the scope of the technical implementation. As such, I'd suggest we merge this PR without any content changes (just added a commit that comments out the content changes), and then I will create a follow up with the content changes which can then be discussed in a separate PR. Please merge this if you agree @mikenikles :)

**Comment by mikenikles** [comment]
This sounds wonderful to me 😄.

**Pull request merged**
