### PR TITLE
[WIP] docs(contribute): companies sharing that they use Gitpod is a form of contribution

### PR DESCRIPTION
**Pull request by ghuntley**
## Description

Companies sharing that they use Gitpod is a form of contribution

Merge this when https://github.com/gitpod-io/gitpod/pull/6641 ships.

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1235"></a>

### CODE REVIEW

**Comment by mikenikles** [comment]
Blocked by https://github.com/gitpod-io/gitpod/pull/6641

**Comment by mikenikles** [comment]
⚠️ This PR will get closed if it's not merged when we migrate the docs into the `gitpod-io/gitpod` repo.

**Comment by ghuntley** [comment]
I will deal with conflicts, please do not close this PR

**Comment by Cahllagerfeld** [comment]
@ghuntley Is this PR still relevant? 😅

**Comment by loujaybee** [comment]
@Cahllagerfeld - I remember the context / converastions behind this, but this is mostly superceded by customer testimonials now: https://www.gitpod.io/customers

Let's close.

**Pull request closed without merging**
