### PR TITLE
[docs] R in gitpod

### PR DESCRIPTION
**Pull request by JesterOrNot**
See #383

### CODE REVIEW

**Comment by svenefftinge** [comment]
nice! Would be good to have info on how to install the R interpreter included. Even better with a nice example showing off something like Shiny or so.

**Comment by jankeromnes** [comment]
Awesome! See also:
- https://github.com/gitpod-io/gitpod/issues/434
- https://twitter.com/gitpod/status/1106532059223347200
- https://github.com/atusy/gitpodr

**Comment by JesterOrNot** [comment]
> Awesome! See also:
> 
> * [gitpod-io/gitpod#434](https://github.com/gitpod-io/gitpod/issues/434)
> * https://twitter.com/gitpod/status/1106532059223347200
> * https://github.com/atusy/gitpodr

I will add these to additional resources

**Comment by JesterOrNot** [comment]
I am resetting this PR as it has gotten very messy!

**Pull request closed without merging**
