### PR TITLE
CDE Adoption Stories with Shares.io

### PR DESCRIPTION
**Pull request by ghostdevv**
Closes MKWEB-107

## Release QA Checklist ✔️

<details>
  <summary>QA Checklist </summary>

## [Priority: High] Functional Testing

-   [x] Test all links to make sure they are working correctly
-   [x] Verify that all forms (sales, support, docs feedback) are functioning properly and data is being captured correctly
-   [x] Check all buttons and calls-to-action to ensure they are leading to the correct pages
-   [x] Ensure that the website is mobile responsive and functions appropriately on different devices
-   [x] Please make sure that page is best for Light/Dark Mode. ⇒ Text/Media Changes

## [Priority: High] Content Testing

-   [x] Check all website copies for accuracy and spelling/grammar errors
-   [x] Verify that all images and videos are displaying properly
-   [x] Ensure that all downloadable files are working correctly
-   [x] Check that all external links are functioning properly

## [Priority: Medium] Performance Testing

-   [x] Try to use optimal media assets. ([Decision Record - How To](https://github.com/gitpod-io/website/blob/main/docs/adr/0003-optimal-assets-format.md))
-   [x] Test website load times to ensure that the website is loading quickly
-   [x] Verify that the website can handle high traffic volumes without crashing
-   [x] Check that all website functionality is working properly under heavy load
-   [x] Perform cross-browser testing to ensure that the website works properly on all major browsers (Google Chrome, Firefox, Edge)

## [Priority: Medium] Accessibility Testing

-   [x] Ensure that the website meets basic accessibility guidelines.
-   [x] Test that users with disabilities can easily navigate and use the website
-   [x] Verify that all website content can be accessed using assistive technologies

By including these key items in your website release QA checklist, you can ensure that your website is fully functional, user-friendly, and meets your business requirements.

## Security Testing

> **Note**:💡 If we are changing something related to cookies, data storing, or analytics.

-   [x] Verify that the website is HTTPS secure and that there are no security vulnerabilities
-   [x] Ensure that all sensitive data is being stored and transmitted securely

</details>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3866"></a>

### CODE REVIEW

**Review by pawlean — APPROVED** [review]
LGTM!

**Comment by pawlean** [comment]
@ghostdevv @chrifro I have an email scheduled for 5PM CET today promoting this webinar, can I have this page reviewed and merged then? I was going to merge it myself but had to update the branch. Once the checks have passed, you can just merge it! :)

**Review by chrifro — COMMENTED** [review]
Nice, thanks @ghostdevv ✨

A few comments:

- [ ]  can you move the registration form further down so that it aligns with the "webinar" tag?

Bildschirmfoto 2023-07-19 um 10 01 49

- [ ] François needs the shares instead of the Gitpod logo. You can find the logo [here](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?type=design&node-id=514%3A2410&mode=design&t=9sdaDUGao8sPKelk-1) Bildschirmfoto 2023-07-19 um 10 03 13

- [x] let's list François before Pauline as he's the guest :) 

- [ ] I don't think we set up a confirmation email. Let's adjust the message to "You'll receive all further information via email" cc @pawlean if you have anything better in mind
Bildschirmfoto 2023-07-19 um 10 13 39

- [ ] this preview image doesn't align with the other previews. Could you align them? 🙏
Bildschirmfoto 2023-07-19 um 10 20 44

- [ ] would suggest removing the style requirements for "company website" in the form. As it could add extra not needed friction. 

I also have some messaging feedback. Where would be the best place to drop that @pawlean ? 😊

**Comment by pawlean** [comment]
webinar

I just updated the messaging, thanks @chrifro for the feedback! @ghostdevv can you take care of the rest? I've also updated the preview image above.

**Review by chrifro — APPROVED** [review]
Approving this PR to not cause any blocking. It's ready to go once the feedback has been addressed 🙌

**Comment by ghostdevv** [comment]
>  would suggest removing the style requirements for "company website" in the form. As it could add extra not needed friction.

I'm not really sure how to do that as the current form system is all over the place :pray:

**Pull request merged**
