### PR TITLE
WIP:  Improve SVG images.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes https://github.com/gitpod-io/website/issues/430#issuecomment-596973755

### CODE REVIEW

**Comment by nisarhassan12** [comment]
> - All characters with the galaxy background

@ChristinFrohne what changes do you want me to make to the characters?

**Comment by ChristinFrohne** [comment]
I mean that the galaxy background needs to be adjusted for all people-icons on the feature page. It's still pixelated.

**Comment by nisarhassan12** [comment]
I'm having an issue with graphic `icon-automated-setup-gitpod.svg` 

looks like this in Chrome:

image

While in Firefox this is how it looks:

image

The same `viewBox` values are giving different results with the change in the browser. I'm not sure how to fix this.

**Comment by ChristinFrohne** [comment]
Is this PR ready to be merged if you leave out the changes for the automated-setup-icon and implement that later?

**Pull request merged**
