### PR TITLE
refactor(troubleshooting): Add info about retrieving workspace data an user

### PR DESCRIPTION
**Pull request by axonasif**
Many people get into trouble but are unsure how to get their data back and continue their work, so this is a repetitive answer to give, which is why adding it here.

## Related Issue(s)

Fixes #

## Release Notes

```release-note
```

## Documentation

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2017"></a>

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2017"></a>

### CODE REVIEW

**Comment by axonasif** [comment]
@Cahllagerfeld any idea why this is failing?

**Comment by axonasif** [comment]
> It looks like an image got linked, that's not there. I'll have a look into it and push a fix 👍

But then it doesn't work outside Gitpod 😅
Initially, I had linked the image like you did(saw it on other pages) but it was important for me to have it work outside Gitpod too as I had to share a [link](https://github.com/gitpod-io/website/blob/85d73232c5356215d3e27c7ef89ff0d3e17e2c78/gitpod/docs/troubleshooting.md#what-can-i-do-if-i-have-unsynced-data-inside-a-workspace-but-its-not-starting) to the doc early without waiting for the PR getting merged.

**Comment by axonasif** [comment]
This worked on both gitpod website and externally IIRC.
https://github.com/gitpod-io/website/blob/081c3591a7e84ad12a286fe11b026aaa023a8fa1/gitpod/docs/troubleshooting.md#what-can-i-do-if-i-have-unsynced-data-inside-a-workspace-but-its-not-starting

**Comment by Cahllagerfeld** [comment]
I don't know the historical context of this in detail, but as far as I know that's a special thing because of the self-hosted docs. Can you explain this in detail @nisarhassan12?

**Review by Cahllagerfeld — APPROVED** [review]
Looks good to me 🚀

**Pull request merged**
