### PR TITLE
Add new subjects to Support

### PR DESCRIPTION
**Pull request by julia-leyton**
## Description
This PR add Question and Issues as subjects to our support.

## Related Issue(s)
None

## How to test
Send a request and check category internally

## Release Notes

```release-note
NONE
```

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/1910"></a>

### CODE REVIEW

**Review by nisarhassan12 — APPROVED** [review]
Thanks, @julia-leyton for the PR it looks good to me 👍🏿 

cc @chrifro or @gtsiolis What do you think about the design here with the labels spanning 3 rows:

image

Once you guys give a go-ahead this Pr can be merged.

**Review by gtsiolis — COMMENTED** [review]
LGTM. 🏁 

**thought**: I'd think the label wrapping issue is an existing issue and out of the scope of this PR. Going from two line to three does not make much of a difference. I'd say it's safe to merge this but I'd defer to @chrifro for making the final call. 🏀 

**suggestion**: Opening a follow up issue to discuss potential further improvements to the subject labels and the wrapping issue would be ideal. ✨ 

Thanks for the ping, @nisarhassan12! 🏓

**Comment by chrifro** [comment]
Thanks, everyone! 🏓
 
I would suggest the following adjustments in a follow-up PR cc @nisarhassan12 
 - reduce the spacing between the subjects to 8 px ([see mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=1%3A8969))
 - not mentioning "abuse report" as it could seem like that's a big issue we are having and that we get many support requests for it. Instead, these requests could be sorted under "other". Then it would also fit in two rows. 
Bildschirmfoto 2022-04-14 um 14 50 34

**Comment by nisarhassan12** [comment]
Fixed in https://github.com/gitpod-io/website/pull/1918/

**Pull request merged**
