### PR TITLE
Update teams and projects roles table to include project settings and project variables

### PR DESCRIPTION
**Pull request by gtsiolis**
## Description

This will update teams and projects roles table, in order to include **project settings** and **project variables**.

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2132"></a>

### CODE REVIEW

**Comment by gtsiolis** [comment]
@jldec What do you think? I was about to reference this table to indicate these two rows and thought it could be helpful to have these here.

**Review by jldec — APPROVED** [review]
LGTM

**Review by Cahllagerfeld — APPROVED** [review]
Awesome 🚀

**Comment by gtsiolis** [comment]
Thanks for taking a look, @Cahllagerfeld @jldec! 🏀

**Pull request merged**
