### PR TITLE
Tone down a few buttons and titles

### PR DESCRIPTION
**Pull request by jankeromnes**

### CODE REVIEW

**Comment by svenefftinge** [comment]
The headers are no sometimes use title case and sometimes not.
Is there any reasoning behind when to use one or the other?

**Comment by jankeromnes** [comment]
No specific reasoning. I just felt that "Titles That Are Very Long Get A Bit Unreadable In Title Case", and that "Do action" buttons are nice, but I didn't want to alter the look & feel of the index page too much, e.g. "Three Ways To Start Coding" is nice and readable, "No Setup", "Less Waiting" and "More Flow" work well with their respective icons, etc.

It's very subjective. Feel free to accept or refuse what feels right.

**Comment by jankeromnes** [comment]
You can also just close this PR, I don't mind. 🙂 (I'm not 100% sure about "Try it now" vs "Try Now", but I do think "Request support" is a bit nicer than "Request Support", for example.)

**Comment by svenefftinge** [comment]
I think it would be good to be consistent. So we decided on going without title case for buttons.
But for titles we usually use title case. it is a bot strange to make a few exceptions. That said I agree long titles get a bit shouty .

**Comment by jankeromnes** [comment]
Let's revisit this later.

**Pull request closed without merging**
