### PR TITLE
Remove team plans from pricing plans

### PR DESCRIPTION
**Pull request by gtsiolis**
## Description

Update plans page, see relevant comment in https://github.com/gitpod-io/gitpod/issues/13229#issuecomment-1264713834.

## Related Issue(s)

Related to https://github.com/gitpod-io/gitpod/issues/13229

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2840"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2840"></a>

### CODE REVIEW

**Review by laushinka — APPROVED** [review]

**Comment by gtsiolis** [comment]
Cc @chrifro

**Comment by gtsiolis** [comment]
Thanks for taking a look, @laushinka! 🍫 

@chrifro Could you take one more look when you're free before merging this?

**Comment by chrifro** [comment]
Thanks for the changes @gtsiolis 🏀 🙏

**Regarding removing team plans:**
Is this FAQ still correct? Should it be updated or removed?
Bildschirmfoto 2022-10-05 um 15 52 40

**Regarding capitalization:**
Thanks for the edits. We have recently agreed on using a sentence case capitalization. For that some items in the table are still off e.g. "Parallel workspaces" "Timeout boost" "Admin dashboard" etc.
But we can also address this in a separate PR

**Comment by gtsiolis** [comment]
Thanks @chrifro for taking a look! 🙏 

**Regarding capitalization**, nice catch! Generally I tend to move such issues to separate follow-up issues, but since I decided to change the comparison table below, I've updated the rest of the features to follow a sentence case capitalization. ✔️ 

**Regarding removing team plans**, this feature still exists and remains the primary way to enable billing for multiple team members. I'd suggest keeping it for now and revisit or consider removing once we switch to UBP (Usage-based Pricing). Opened https://github.com/gitpod-io/website/issues/2860 to keep track of this. 🏓 

I'll merge this MVC once the preview deployment is up and running.

**Pull request merged**
