### PR TITLE
[docs]: Visual differentiator for external links. 

### PR DESCRIPTION
**Pull request by nisarhassan12**
This is how it looks:

image

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/484"></a>

### CODE REVIEW

**Comment by JohannesLandgraf** [comment]
I think it looks better if the icon comes after the link - also places more emphasis on content instead of link as you read from left to right

**Comment by nisarhassan12** [comment]
Thanks, @JohannesLandgraf for the feedback it indeed looks a lot better if the icon appears after the content 
image

I have made the change.

**Comment by ChristinFrohne** [comment]
I'd suggest just using the arrow of the icon, the look would then be a lot cleaner/simpler. Netlify and Raycast do it similarly.  
Bildschirmfoto 2021-05-25 um 14 15 05
Bildschirmfoto 2021-05-25 um 14 17 03

**Comment by nisarhassan12** [comment]
I have updated the icon this is how it looks now:

image

**Pull request merged**
