### PR TITLE
add browser extension flow pages. 

### PR DESCRIPTION
**Pull request by nisarhassan12**

### CODE REVIEW

**Comment by ChristinFrohne** [comment]
Thanks, @nisarhassan12 

Here are a few comments

**Activation page:**
- [ ] the screenshot seems blurry, please use the attached file
Github-gitpod-button

- [ ] there should be no `reinstall extension`button on the activation page

**Uninstall page:**

- [ ] the text in the button `reinstall extension` is not centered. Please align it

- [ ] `reinstall extension`should link to the correlated Chrome or Firefox extension 

- [ ] The URL `/extension-uninstall` fits better than `/extension-deletion`

- [ ] sending the form should also be allowed when using the text field 

Would be great to connect the user feedback to our data bank. Where is the feedback currently send to? I'll discuss that with Johannes as well

**Comment by nisarhassan12** [comment]
>  the text in the button reinstall extension is not centered. Please align it

Thanks. @ChristinFrohne for the feedback. I'm unable to re-produce this. Can you share zoomed-in screenshots of this issue ? The button has the same amounts of paddings for the left/right and the top/bottom to give the centered look to the text inside.  

image

**Comment by nisarhassan12** [comment]
> Would be great to connect the user feedback to our data bank. Where is the feedback currently send to? I'll discuss that with Johannes as well

The feedback is sent to the place where the data for other contacts forms is sent. I don't have access to that place. Someone with access to that place should test whether the data gets submitted correctly or not.

**Comment by nisarhassan12** [comment]
@ChristinFrohne I changed the minimal Footer to have the mention of Gitpod as opposed to TypeFox like we recently did for the main primary Footer.

**Comment by ChristinFrohne** [comment]
Thanks for fixing the outstanding issues

>I'm unable to re-produce this. Can you share zoomed-in screenshots of this issue ?

It's a minor issue, but it seems that the text box has more spacing below the text than above. Or is it because there are no descending letters?
Bildschirmfoto 2020-12-28 um 14 33 48

**Comment by ChristinFrohne** [comment]
@george you suggested duplicating the GitLab, GitHub and Bitbucket buttons above the screenshot. Are you fine creating the first version like this and iterating on it afterwards? Otherwise, please add your suggestion to the PR.

**Comment by ChristinFrohne** [comment]
What would be the best way to collect the user feedback? @JohannesLandgraf @jankeromnes 
Can we connect it directly to our data bank? 
I just sent a `test` feedback, but I couldn't find it anywhere. 

Bildschirmfoto 2020-12-28 um 15 00 17

**Comment by nisarhassan12** [comment]
> It's a minor issue, but it seems that the text box has more spacing below the text than above. Or is it because there are no descending letters?
@ChristinFrohne You are right it's because there are no descenders. I just tried adding one it looks perfectly centred to me. 

image

**Comment by nisarhassan12** [comment]
@ChristinFrohne for figuring out where the data submited on /extension-uninstall goes let's maybe merge this PR without publicly mentioning or linking to the pages that it adds anywhere ? I think the data will go to the same place as is the case for other forms in production.

**Comment by ChristinFrohne** [comment]
Sounds good, let's merge and test it.

**Comment by mikenikles** [comment]
@nisarhassan12 & @ChristinFrohne do you recall testing the form submission for the "uninstall browser extension" page? I don't see any emails that match.

I worked on the migration of this page to the new website today and noticed the form doesn't get submitted. This is also the case on the current production site. I'll look into it to see what may cause it.

**Comment by mikenikles** [comment]
That was quicker than expected... The email in this PR is missing `from` information, hence users cannot submit the form successfully. A fix is applied to the new website.

**Comment by ChristinFrohne** [comment]
For more information see #1009

**Pull request merged**
