### PR TITLE
Added mission + streamlined existing and added design opening

### PR DESCRIPTION
**Pull request by JohannesLandgraf**

### CODE REVIEW

**Comment by JohannesLandgraf** [comment]
@nisarhassan12 Can you make each of the first sentences in ALL the openings bold? Not sure how I do that in React. Thanks! 

I.e. 

As part of the team you will ...

- **Directly impact users**. Gitpod has little fat to trim and changes directly affect users. We always have our users in mind and focus on making Gitpod work for them, not some abstract potential future requirement.
- **Be a "jack of all trades, master of some"**. As a small team we favour generalists. You might work on React code, or dive into the backend. There is loads of room to find your passion and see everything that makes the platform tick.

**Comment by JohannesLandgraf** [comment]
@nisarhassan12 Can you resolve the conflicts - not exactly sure what to do here? Thanks!

**Comment by nisarhassan12** [comment]
@JohannesLandgraf I have resolved the conflicts please have a look again. Thanks

**Comment by meysholdt** [comment]
merging, since @JohannesLandgraf was satisfied with this PR yesterday and I need to base on it today.

**Pull request merged**
