### PR TITLE
feat(humanstxt): create humans.txt

### PR DESCRIPTION
**Pull request by ghuntley**
## Description

Introduces www.gitpod.io/humans.txt

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1189"></a>

### CODE REVIEW

**Review by gtsiolis — COMMENTED** [review]
Hey @ghuntley! Here're some thoughts on this change:

**issue**: The main issue here is that we would need to keep this up-to-date along the way. Besides small updates in the first paragraphs that could be needed, the country count could easily become outdated. 

**thought**: Not sure how much value adding a `humans.txt` could provide since there's a trend[[1](https://www.mozilla.org/humans.txt)][[2](https://www.uber.com/humans.txt)][...] in removing `humans.txt` in some products or redirecting to `/about`[[3](https://en.wikipedia.org/wiki/Robots_exclusion_standard#Alternatives)].

**suggestion**: We could :a: either move this forward with a simpler form[[4](https://www.google.com/humans.txt)][[5](https://www.netflix.com/humans.txt)] that needs less effort on keeping up-to-date or :b: simply redirect `/humans.txt` to [`/about`](https://www.gitpod.io/about)?

**Comment by mikenikles** [comment]
My vote is for 🅱️.

From their website (https://humanstxt.org/):
> It's an initiative for knowing the people behind a website. It's a TXT file that contains information about the different people who have contributed to building the website.

GitHub does a fantastic job at this, see [Contributors](https://github.com/gitpod-io/website/graphs/contributors).

**Comment by ghuntley** [comment]
I'd prefer to change the language and words and have this as a classy Easter egg then redirect to /contributors or /about. See www.Netflix.com/humans.txt

**Comment by mikenikles** [comment]
An Easter egg sounds fun, as long as we don't duplicate information that needs to be kept up-to-date.

**Comment by mikenikles** [comment]
Cleaning up open & stale PRs. Please re-open if this is still something we want to add.

**Pull request closed without merging**
