### PR TITLE
Update 'Trusted by' logos

### PR DESCRIPTION
**Pull request by jankeromnes**
Fixes https://github.com/gitpod-io/website/issues/594

### CODE REVIEW

**Comment by ChristinFrohne** [comment]
Thanks for adjusting the colors again. It's looks lots better now!
It seems like the "freecodecamp" logo got down scaled in the process. Can that be adjusted here or does it need a new issue? 
Bildschirmfoto 2020-04-29 um 12 47 57

**Comment by jankeromnes** [comment]
Interesting. This is what https://www.gitpod.io looks like for me currently:

Screenshot 2020-04-29 at 13 38 11

@ChristinFrohne Which browser are you using? Could you please provide a full-window screenshot?

**Comment by jankeromnes** [comment]
Nevermind, it looks like Chrome doesn't understand `transform: scale(150%)`:

Screenshot 2020-04-29 at 13 45 02

I guess it wants `transform: scale(1.5)` instead. Oh well.

**Comment by jankeromnes** [comment]
Should be fixed in https://github.com/gitpod-io/website/commit/6477719bc4ec52790f733d7edd1b60ec85bfa025

Thanks for reporting!

**Comment by ChristinFrohne** [comment]
Great. I can confirm that it's fixed. 

The spacing between the logos is inconsistent though. Also, I like your suggestion of enabling a horizontal scrolling. I created an issue for it both #600

**Pull request merged**
