### PR TITLE
fix: 404 page render in prod.

### LINKED ISSUE #1479: Error 404 Page Not Rendering in Production
## Description
Error 404 page not working in Production, while it is working in local.

## Regenerate this issue
- Go to Any endpoint which doesn't exist, like this [`/errorxyz`](https://www.gitpod.io/errorxyz)

## Related
- https://github.com/sveltejs/kit/issues/930
- [gitpod website's `__error.svelte` file]( https://github.com/gitpod-io/website/blob/main/src/routes/__error.svelte)
- https://github.com/gitpod-io/website/blob/03fe6677cb239af769683e7e99f240988a3c58a5/src/routes/blog/from-gatsby-to-svelte.md#L81

## Video Demo

<a href="https://www.loom.com/share/4d15f8dbf4d0435c8b7020030316606d" target="_blank">
    <p>www.gitpod.io - error page in production - Watch Video</p>
    
</a>

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

This PR aims to fix #1479. So, If any user will redirect to any invalid URL. It will be redirected to 404 Page.

## How to Test
- Open this Invalid URL: https://deploy-preview-2611--gitpod-kumquat.netlify.app/invalid-random-url

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2611"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2611"></a>

### CODE REVIEW

**Review by Cahllagerfeld — COMMENTED** [review]
I feel like turning `split` to false without enabling edge funciton might do the trick already for fixing the 404 issue 🤔

**Comment by Siddhant-K-code** [comment]
> I feel like turning `split` to false without enabling edge funciton might do the trick already for fixing the 404 issue

yes, it was working with prev. commit (without `edge: true,`). Was Just testing out edge functions. In sync call, I got to know about the version bump.

**Review by Cahllagerfeld — APPROVED** [review]
Could you please test a docs-widget and contact + sales forms before merging 👍 Other than that lets merge it I think

**Comment by Siddhant-K-code** [comment]
It is reverted for time being in https://github.com/gitpod-io/website/pull/2665

**Comment by Cahllagerfeld** [comment]
Thanks for linking the PR here @Siddhant-K-code 

We may handle it with a custom 404 route on our app, and let Netlify redirect there [[1](https://blog.kiprosh.com/show-custom-404-error-page-for-netlify-applications/)] this might work also with the split activated, in case that's making a huge difference

**Pull request merged**
