### PR TITLE
create the unsubscribe page + fix some other issues.

### PR DESCRIPTION
**Pull request by nisarhassan12**
This is how it looks:

image

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/848"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/848"></a>

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Hey @ChristinFrohne In the Pr @laushinka  and I have updated the illustration for the Contact form which appears when the form is submitted successfully. Let us know What you think about that.

**Review by ChristinFrohne — COMMENTED** [review]
Awesome, thanks!

It would be best if the whole content is visible without scrolling. 
We don't need to have a footer on this page. Can you move the box a bit further up and adjust the image size?
See [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=1254%3A687)
Thanks!

**Review by pawlean — APPROVED** [review]
I just changed the URL to the image because it was broken. Other than that it looks good to me.

**Comment by laushinka** [comment]
> I just changed the URL to the image because it was broken. Other than that it looks good to me.

Thank youuu

**Comment by JohannesLandgraf** [comment]
lgtm lets merge :)

**Comment by pawlean** [comment]
You're good to go, @laushinka!

**Pull request merged**
