### PR TITLE
add secondary cta to contact sales on the landing page.

### LINKED ISSUE #2155: Add secondary CTA to contact sales on landing page
**Why?** 
we should make it's as easy as possible for enterprise customers to contact us.

**Changes:**
- add secondary CTA "Get a demo" next to "try now"
- update layout around both CTAs
- move link to GitHub stars to navigation

[mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5186%3A9965):

|status quo| new suggestion|
|-|-|
|Bildschirmfoto 2022-05-31 um 16 15 11|Bildschirmfoto 2022-05-31 um 16 20 58

Related issue #2153 and #2154 (the contact button needs to be moved first from the navigation bar before there is space for the GitHub stars)

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #2155 

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2352"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2352"></a>

### CODE REVIEW

**Comment by chrifro** [comment]
Nice @nisarhassan12 ! ✨

Some comments:

- [ ] could you use the same style for the GitHub stars as suggested in the [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5186%3A9965)
Bildschirmfoto 2022-07-05 um 08 38 17

- [ ] we should watch out to have a consistent upper/lower case styling. E.g. here the buttons are not aligned. Let's only use upper case for the first letter and proper names, so it would be `Try now`

>ATM the GitHub stars widget is not shown on mobile where do we plan to show it on mobile? 

I added a mockup for it [here](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5586%3A7477). 
Bildschirmfoto 2022-07-05 um 08 37 12

**Comment by nisarhassan12** [comment]
Thanks for the review @chrifro 

> - [ ] could you use the same style for the GitHub stars as suggested in the [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5186%3A9965)

Unfortunately, we don't control the way this stars widget looks. It's a third-party widget.

**Comment by chrifro** [comment]
>Unfortunately, we don't control the way this stars widget looks. It's a third-party widget.

Couldn't we use the same style as https://www.timescale.com/ is using? 

 https://www.appsmith.com/blog/building-a-github-star-tracker-for-your-open-source-project seems helpful as well

**Comment by chrifro** [comment]
I'm fine with merging this as a first iteration but there should be a follow-up issue soon. I talked with some others and currently, it's not very clear that the stars indicate the GitHub stars. The other design is more intuitive and visually less distracting.
Thanks! :)

**Comment by nisarhassan12** [comment]
Thanks, @chrifro I have opened a new issue #2378  and moved that to the scheduled column and will try to get it live by the end of the next week FYI I'm OOO for the first 2 days next week.

**Pull request merged**
