### PR TITLE
add features page 

### LINKED ISSUE #3: Features
This is the current layout for the features

features new

### PR DESCRIPTION
**Pull request by jankeromnes**
Fixes #3.

I've also added a debug mode to the StarGraph which shows coordinates when you hover on stars (also wanted to make them draggable for convenience, but didn't want to spend too much time on it).

The page currently looks like this:
<details>
  <summary>(old screenshot)</summary>

screenshot_2019-03-08 gitpod

</details>
<br>

ToDo:
- I don't really like listing all the features at the top as in the concept (feels like duplicated content). Is that necessary / can we find another way?
- "Prebuilt Workspaces" and "Linux in Your Browser" features are missing screenshots & descriptions
- The video link should open a modal video instead of opening a new link on YouTube
- What should the "support" and "get started" links point to?

### CODE REVIEW

**Comment by jankeromnes** [comment]
@svenefftinge Sorry, I tried to not make a pull request, but I need your input and didn't want to push an unfinished page. 😛

**Comment by svenefftinge** [comment]
> I don't really like listing all the features at the top as in the concept (feels like duplicated content). Is that necessary / can we find another way?

I like it very much. I think it is more like a TOC, i.e. a quick overview with quick navigation of the features.

**Comment by jankeromnes** [comment]
Ok fair enough, I'll try with the table of contents.

Also I believe the wording can be improved, so I've given some more thought on "why Gitpod". Will share my ideas soon.

**Comment by jankeromnes** [comment]
New work-in-progress:

Screenshot_2019-03-11 Gitpod

**Comment by jankeromnes** [comment]
New work-in-progress (with updated wording, texts, and two more screenshots):

Screenshot_2019-03-12 Gitpod

**Comment by jankeromnes** [comment]
Ok, here was the last round of feedback, I'll try to address all items (or leave them as follow-ups) and then merge the features page, to have it with the rest of the website.

- [ ] Docker: maybe mention the automated setup, at least in the paragraph, rename headline to "integrates Docker"?
- [ ] VS Code: maybe rename to "based on VS Code" Does anyone know Theia? Maybe mentioning that it's an open-source IDE is helpful?
- [ ] can we add buttons to more information about Linux and Prebuilt workspaces?
- [ ] any reason why you don't use the crosses for features which we don't support in the table?
- [ ] the ticks could be thinner
- [ ] the table column width should be consistent
- [ ] there should be more space below the ‘linux’ section
- [ ] the star graph connection before the ‘docker’ heading doesn’t align in height (I see why it is but I’m not quite happy with the solution)

**Comment by jankeromnes** [comment]
Also, here is an alternative design mockup:

Features – new – 2

**Comment by jankeromnes** [comment]
Merged as a1d33870b32f05aef981b723b6d07476a61aeaa7.

**Pull request closed without merging**
