### PR TITLE
Add PlanetScale quickstart guide

### PR DESCRIPTION
**Pull request by Shulammite-Aso**
## Description

Adds a quickstart guide for [PlanetScale](https://planetscale.com/). 
For the template linked on the guide, the .gitpod.yml file pulls the docker image for PlanetScale CLI(pscale ) then creates  a shell alias that runs the latest version of pscale from docker whenever the user runs a `pscale` command.

## Related Issue(s)

Fixes #

## Release Notes

```release-note
```

## Documentation

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1259"></a>

### CODE REVIEW

**Comment by Shulammite-Aso** [comment]
I thought it would be nice if config also ran the pscale auth command `pscale auth login` to prompt the user to authenticate once the workspace starts up, but at the moment i have gotten that to run fine as the command returns `pscale: command not found`. But one can manually run the command when the workspace has fully started and it would work just fine.

It looks as if the `pscale auth login` runs before the shell alias gets created. Haven't understood why yet as I see that commands should run in the order they are provided.
E.g i had initiatlly:
```
command: |
      mkdir -p $HOME/.config/planetscale
      alias pscale="docker run -e HOME=/tmp -v $HOME/.config/planetscale:/tmp/.config/planetscale --user $(id -u):$(id -g) --rm -it -p 3306:3306/tcp planetscale/pscale:latest"
     pscale auth login
```

**Comment by Shulammite-Aso** [comment]
@JohannesLandgraf take a look

**Comment by Shulammite-Aso** [comment]
>  but at the moment i have gotten that to run fine as the command returns `pscale: command not found`. But one can manually run the command or any `pscale` command when the workspace has fully started and it would work just fine.

I can confirm now that this in not peculiar to gitpod or that very configuration. Joining those commands together with `&&` operator on any other linux environment has returned the same result: `bash: pscale: command not found`. But of course, when run on seperate lines it works just fine.

**Comment by svenefftinge** [comment]
Hi @Shulammite-Aso, thank you so much for the contribution. I'm trying the docs and noticed that [the repo](https://github.com/Shulammite-Aso/template-planetscale) you've setup is not marked as a template. Could you please change that?

**Comment by Shulammite-Aso** [comment]
Hi @svenefftinge, sorry about that, I've just marked it as one

**Comment by Shulammite-Aso** [comment]
Hi @svenefftinge, just wanted to make sure you saw my last ping

**Comment by gtsiolis** [comment]
Thanks @Shulammite-Aso! 🙌 

Let me loop in @mikenikles and @ghuntley in case they could take a look or forward to someone on the team. 🏓

**Comment by mikenikles** [comment]
Thank you for the ping @gtsiolis.

Hi @Shulammite-Aso, nice work with that repo - it works as expected. Could you please update the repository's "About" section to match what we have in the template at https://github.com/gitpod-io/template-template?

There's also a URL to bet set to www.gitpod.io and topics you can specify, it'd be great to add `gitpod` and `planetscale` as topics 🙏.

☝️ isn't blocking this PR from getting merge.

**Pull request merged**
