### PR TITLE
fix headlines order for better accessibility and seo.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Addresses the following from #842 

image

### Why this is important:

According to https://www.w3.org/WAI/tutorials/page-structure/headings/

image

### CODE REVIEW

**Comment by nisarhassan12** [comment]
I have corrected the order of the headings for all the pages of the site including the docs. On the blog, the heading order still needs to be corrected. @ChristinFrohne @JohannesLandgraf Can I change the order of the headings in the blog posts as well? Thanks

**Comment by ChristinFrohne** [comment]
Thanks @nisarhassan12 
Looks good. It's fine if you change the headline style without asking the author of each blog post. Your changes won't influence the content, so it's fine.

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made the changes to the blog posts as well. Please have a look again when you'll have time. Thanks

**Review by ChristinFrohne — APPROVED** [review]
Looks good! Thanks

**Comment by nisarhassan12** [comment]
Thanks, @ChristinFrohne for the review. I'll merge this after doing a final self-review to see if there aren't any pages that are leftout.

**Pull request merged**
