### PR TITLE
fix: code block in collaboration page

### LINKED ISSUE #2811: [Docs Feedback]: Code blocks not working in toggle tabs
### Page URL

https://www.gitpod.io/docs/sharing-and-collaboration

### User feedback

image

`gp snapshot` is not rendering as code

### PR DESCRIPTION
**Pull request by Asmit2952**
## Description

Fixed a code block in collaboration page under toggle tabs. It wasn't rendering as expected.

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2887"></a>

### CODE REVIEW

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
https://github.com/gitpod-io/website/issues/2811 indicates that it should render code blocks in toggle tabs without adding explicit `<code>`

**Comment by Asmit2952** [comment]
> #2811 indicates that it should render code blocks in toggle tabs without adding explicit `<code>`

Hey @Siddhant-K-code, I did try using single quotes and it didn't render. Then I looked at Ports.md file which had similar toggle tabs. The toggle tabs are written under HTML code blocks, so back ticks won't work. Therefore, I had to use explicit `<code>` tag.
Here's the file: https://github.com/gitpod-io/website/blob/main/gitpod/docs/configure/workspaces/ports.md#specify-port-names--descriptions

**Comment by Siddhant-K-code** [comment]
Then, I think we need to add support for the code rendering in tabs too as we have normally on other parts of the website.

**Comment by Asmit2952** [comment]
> Then, I think we need to add support for the code rendering in tabs too as we have normally on other parts of the website.

But isn't that automatically rendered with Svelte? Like we just targeted code tag using tailwind CSS I think. So whenever back ticks are used in md, it renders as code.

Also, can we merge this PR if you think it's fine?

**Comment by Asmit2952** [comment]
Hey @Siddhant-K-code can we merge this?

**Comment by Asmit2952** [comment]
Hey @Siddhant-K-code after investigating, I found out that what we want to achieve is render code blocks using backticks in toggle tabs as we do it everywhere in the docs. This is more like a quick typo fix! I will search more about how to render markdown in html blocks and hopefully will find something.

**Review by Siddhant-K-code — APPROVED** [review]
:shipit: as 🛹 Solution, we can evaluate the more optimal solution later on.

**Comment by Siddhant-K-code** [comment]
Thanks, @Asmit2952 for the contribution ✨

Looping in @meysholdt for CLA Signing 🙌🏼

**Comment by Siddhant-K-code** [comment]
For us to be able to merge this PR, can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via [siddhant@gitpod.io](mailto:siddhant@gitpod.io)

**Comment by Asmit2952** [comment]
> For us to be able to merge this PR, can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via [siddhant@gitpod.io](mailto:siddhant@gitpod.io)

Signed the CLA :)

**Comment by Siddhant-K-code** [comment]
> > For us to be able to merge this PR, can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via [siddhant@gitpod.io](mailto:siddhant@gitpod.io)

> Signed the CLA :)

@meysholdt Can you please confirm that?

**Comment by Asmit2952** [comment]
> > > For us to be able to merge this PR, can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)? If there are any questions, you can reach me via [siddhant@gitpod.io](mailto:siddhant@gitpod.io)
> 
> > Signed the CLA :)
> 
> @meysholdt Can you please confirm that?

Should I share the screenshot? @Siddhant-K-code

**Comment by Asmit2952** [comment]
Hey are there any updates on this @meysholdt @Siddhant-K-code? Or do I need to provide screenshots?

**Comment by Siddhant-K-code** [comment]
Thanks, @Asmit2952 for contribution & signing our CLA 🧡

**Pull request merged**
