### PR TITLE
improve the testimonials

### LINKED ISSUE #2167: Improve twitter quotes
**Changes**:
- [x] I tried to highlight the companies more and to make the advocate look more connected to Gitpod (orange frame, monochrome picture)
- [ ] Add company logo
- [x] updated headline to be more enterprise focussed
- [x] remove the link to Twitter to not drive visitors away from our website  [[1](https://www.notion.so/gitpod/Improve-website-for-enterprise-77d5f8a8b97f40fe9d99f6862225f899#73d6e2c466ba41ee94ff44177e2b3b5e)]

[Mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=5186%3A9965):
Bildschirmfoto 2022-06-02 um 10 48 13

**Next steps:**
- update the current quotes
- add additional quotes (replace old quotes) -> see [here](https://www.notion.so/gitpod/Improve-website-for-enterprise-77d5f8a8b97f40fe9d99f6862225f899#0b9f878ee6d6494e8cf7404427334e58) for inspiration @MichaelAring

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #2167 and #143 

- [x] Drag and Drop Scorll on Desktop

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2240"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2240"></a>

### CODE REVIEW

**Comment by nisarhassan12** [comment]
@chrifro I have checked the todos that are done in the relevant issues https://github.com/gitpod-io/website/issues/2167 https://github.com/gitpod-io/website/issues/143 

What do you think about the animation for the carousel? Thanks

**Comment by mikenikles** [comment]
@nisarhassan12 is this something that's still on your radar to work on? I'm working my way through the oldest open issues, trying to close them one by one.

**Comment by nisarhassan12** [comment]
Thanks, @mikenikles Yes. It is still on my radar.

**Comment by nisarhassan12** [comment]
> - [ ] dark theme: the circles around the images need to be adjusted
@chrifro What adjustments should I make for the dark mode? 

> - [ ] animations should look like I'm scrolling through it with the mouse. It just quickly scrolls to the next 3 quotes when clicking on one of the dots

Also, can you share any examples of it that I can follow?

**Comment by chrifro** [comment]
> dark theme: the circles around the images need to be adjusted
> >@chrifro What adjustments should I make for the dark mode?

The gradient stroke around the images was white instead of black (see screenshot of the previous comment)


> animations should look like I'm scrolling through it with the mouse. It just quickly scrolls to the next 3 quotes when clicking on one of the dots
> >Also, can you share any examples of it that I can follow?

The animation could be similar to the one on https://airbyte.com/ only that we show several quotes instead of one

**Pull request merged**
