### PR TITLE
feat: replace logos with svg

### LINKED ISSUE #1821: /customers quotes section logos are blurry on Chrome and Brave
| Chrome, Brave | Firefox |
| - | - |
| Screen Shot 2022-03-24 at 5 41 51 PM | image |

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #1821

- [x] Vizlib
- [x] Shares
- [x] Redwood

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/1840"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1840"></a>

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
I replaced the two logos, we're already having.. Could you please check with them @nisarhassan12 if it makes a difference for you please?

**Comment by nisarhassan12** [comment]
> I replaced the two logos, we're already having.. Could you please check with them @nisarhassan12 if it makes a difference for you please?

Thanks, @Cahllagerfeld It indeed looks a lot better now on Chrome for the 2 logos that you replaced i.e they are no longer blurred.

**Comment by chrifro** [comment]
You mentioned before that you had troubles finding an .svg for Redwoodjs @Cahllagerfeld. Here it is:
logo
Most logos (all svg) can also be found in the [component library](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A2410)

**Comment by Cahllagerfeld** [comment]
Thanks @chrifro 🙏  I had a look at the component library, but wasn't sure because at the current website we are using this image with this little illustration in front of it.
grafik

**Comment by nisarhassan12** [comment]
Thanks, @chrifro at the moment in the quotes section we use the Redwood JS logo with a mark and not just text. Can you add the SVG logo with the mark to the component library as well ? Thanks 

I tried but I was not able to find an SVG for that earlier as specified here https://github.com/gitpod-io/website/issues/1821#issuecomment-1081938816 in case we are not able to find the SVG we could either leave it as it is or use the logo without the mark. In that case, it might not look consistent as the other logos are not just text they also have a mark with them.   

image

**Comment by nisarhassan12** [comment]
@Cahllagerfeld I have merged the PR because I have already updated the Redwood JS logo in https://github.com/gitpod-io/website/pull/1901

**Pull request merged**
