### PR TITLE
Mention CLA in "Submitting a pull request" page

### PR DESCRIPTION
**Pull request by jankeromnes**
## Description

Mention CLA in "Submitting a pull request" page

## Related Issue(s)

Fixes [Slack thread](https://gitpod.slack.com/archives/C04JEP60Q9X/p1675884821232019?thread_ts=1675883877.945819&cid=C04JEP60Q9X) (internal)

## Release Notes

```release-note

```

### CODE REVIEW

**Review by Siddhant-K-code — COMMENTED** [review]
Can we mention the Link in our PR Template & Information on the website? Because some folks can spam if they would find direct link on website

**Comment by jankeromnes** [comment]
Thanks for the review! I would like to move forward on this (independently of other improvements like PR templates and such).

@meysholdt do you think this change is okay & valuable as is?
- If yes, I'd like to merge it
- If no, I'd like to close it unmerged

**Comment by jankeromnes** [comment]
Ping @meysholdt

**Comment by jankeromnes** [comment]
Ping @meysholdt

**Comment by jankeromnes** [comment]
Giving up.

**Pull request closed without merging**
