### PR TITLE
Fix figcaption sveltekit warnings

### PR DESCRIPTION
**Pull request by pavelloz**
## Description
Fixes build warnings during `npm run build`

```
[vite-plugin-svelte] /Users/pavel/projects/gitpod-website/src/routes/guides/connect-multiple-repositories-using-tailscale/index.md:37:0 A11y: <figcaption> must be an immediate child of <figure>
35: <figure>
36: <center><img src="/images/guides/connect-multiple-repositories-using-tailscale/locahost-ssr.png" alt="Multiple services can communincate with each-other when running on the same machine" width=500/>
37: <figcaption>Local setup</figcaption>
^
38: </center>
39: </figure>
```

## How to test
`npm run build`

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1998"></a>

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
Thanks for your contribution 🚀 I accepted the Deployment, so you get a preview-environment for the changes once the Netlify-Deployment is finished :)

**Comment by pavelloz** [comment]
Thank you :)

It seems like it is good on preview :)

Before:
image


After:
image

**Review by nisarhassan12 — APPROVED** [review]

**Comment by nisarhassan12** [comment]
Thanks, @pavelloz for the PR. LGTM 👍🏿

**Comment by pavelloz** [comment]
👍

**Pull request merged**
