### PR TITLE
add anouncement banner.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes gitpod-io/website#713

### CODE REVIEW

**Comment by ChristinFrohne** [comment]
Great, thanks!

- [ ] The image is not sharp, please use this file instead: 

Celebration header-06

- [ ] please add a hover effect for the exit-icon (black circle with a white x - see mockup)

- [ ] the text changed slightly to "Gitpod Is Now Open Source. Learn More"

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made the requested changes please have a look again.

**Comment by ChristinFrohne** [comment]
Great! Two nits:

- [ ] the banner should not be visible on other pages after I once closed it

- [ ] the link will be https://www.gitpod.io/blog/opensource/

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made the requested changes please have a look again. Thanks

**Comment by ChristinFrohne** [comment]
The banner is still shortly displayed after closing it. It shortly shows up on every new page

**Comment by nisarhassan12** [comment]
> The banner is still shortly displayed after closing it. It shortly shows up on every new page

@ChristinFrohne This does not happen on my end. That's probably because you visited the deploy preview when the changes were maybe not deployed. Please try again and it will hopefully work.

**Comment by ChristinFrohne** [comment]
Still the same. See

[Bildschirmvideo aufnehmen 2020-08-25 um 11.37.52.zip](https://github.com/gitpod-io/website/files/5122871/Bildschirmvideo.aufnehmen.2020-08-25.um.11.37.52.zip)

**Comment by nisarhassan12** [comment]
Thanks. 
Sorry, Now I see the issue.

**Pull request merged**
