### PR TITLE
render post previews below every post.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes gitpod-io/website#803

### CODE REVIEW

**Comment by ChristinFrohne** [comment]
Thanks!

- [ ] Could you adjust the background image like it's done in the mockup
Bildschirmfoto 2020-10-29 um 12 05 27
Bildschirmfoto 2020-10-29 um 12 06 19

- [ ] could you add the option to share the blog post to the bottom of the post as well (see mockup)

- [ ] can you always display the last three blog posts in the preview and enable a horizontal sliding to see the other blog posts?

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made the changes please have a look again. 

> can you always display the last three blog posts in the preview and enable a horizontal sliding to see the other blog posts?

Yes. I can try to implement it but it will take some time. Let Open a new issue if this is important.

**Comment by ChristinFrohne** [comment]
- [ ] please remember to add the hover style to all share-icons 

- [ ] if the sliding is more complicated to implement, could you then always display the latest 3 blog posts. They should be the most relevant to the user

**Comment by nisarhassan12** [comment]
> if the sliding is more complicated to implement, could you then always display the latest 3 blog posts. They should be the most relevant to the user

@ChristinFrohne yeah the sliding is more complicated but can be implemented and would be a nicer experience in my opinion. Regarding always displaying the latest 3 blog posts what about when the user is on one of the 3 latest posts ? Thanks.

**Comment by ChristinFrohne** [comment]
>Regarding always displaying the latest 3 blog posts what about when the user is on one of the 3 latest posts ?

Then the users should see the previous blog post. E.g. if they just read the latest one, the three former blog posts should be displayed. 

Let's do it like this and if we see that the blog post preview has a big influence on the user behavior we can improve this section by adding the sliding. We can track the users' behavior via Google Analytics. There we can measure the exit rate and observe the following page visits.

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made the requested changes. Please have a look again i.e now the latest 3 blogs posts are displayed on every post apart from the first 3 i.e for them the former 3 posts are gonna be rendered.

**Review by ChristinFrohne — APPROVED** [review]
Looks good now. Thanks!

**Pull request merged**
