### PR TITLE
Redirect community.gitpod.io to /chat

### PR DESCRIPTION
**Pull request by meysholdt**
## Description
redirect requests from community.gitpod.io to www.gitpod.io/chat

I have added community.gitpod.io as a domain alias in Netlify.

## Related Issue(s)
Fixes https://github.com/gitpod-io/ops/issues/396

## How to test
Not sure if this can be tested in Netlify's preview envs - because they don't reflect the subdomain.

## Release Notes

```release-note
NONE
```

## Documentation

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2483"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2483"></a>

### CODE REVIEW

**Comment by meysholdt** [comment]
I'm afraid so :(

**Review by Cahllagerfeld — APPROVED** [review]
Let's get it merged then 🛹

**Comment by meysholdt** [comment]
🚀 🔥

**Comment by meysholdt** [comment]
> 4:09:37 PM: Site is live ✨

https://community.gitpod.io/foobar --> gets redirected successfully
https://community.gitpod.io/ --> does not get redirected

**Comment by Cahllagerfeld** [comment]
Do you think it has something to do with the wildcard `https://community.gitpod.io/*`? It seems like it's only fired if we have anything behind the last slash. We may need a second rule for the root, what do you think? 🤔

**Comment by meysholdt** [comment]
yes, I think it's exactly as you describe it. Here is the PR for add the second rule: https://github.com/gitpod-io/website/pull/2485

**Pull request merged**
