### PR TITLE
fix: lazy load images

### LINKED ISSUE #1850: Lazy load images to enhance page load times.
On the [Changelog](https://www.gitpod.io/changelog) the lighthouse score is 50 and that is because of the fact that all the changelog entries images are loaded on the initial page load.

image

The problem with loading all the images that a page has is that we are never sure if for instance a user will scroll down and see them all thus resulting in unnecessary usage of bandwidth which we can avoid via lazy loading. Lazy loading will help improve the overall performance scores as well.

### PR DESCRIPTION
**Pull request by jacobparis**
## Description

- Lazy loads all Markdown images as well as below-the-fold images for the changelog index
- Adds automatic image dimensioning to our markdown

image

## Related Issue(s)

Fixes #1850
Closes #1878 

## How to test

Go to /changelog, blog, guide pages
- Images should have dimensions
- Open network tab. Images should download as you scroll

Check lighthouse in incognito mode for improved scoring

## Release Notes

```release-note
```

## Documentation

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2791"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2791"></a>

### CODE REVIEW

**Review by Cahllagerfeld — COMMENTED** [review]
Do you think it also makes sense to add this lazy-loading to all landing pages?

**Comment by jacobparis** [comment]
I do agree with that, and for the most part I think we won't have too much issue doing so. We should only be doing it to below the fold images, so any component that is sometimes shown above the fold and sometimes below will be unoptimal, but I suspect those cases are rare

**Comment by Siddhant-K-code** [comment]
Thanks a lot for raising the PR.

are you running a [Lighthouse report](https://pagespeed.web.dev/report?url=https%3A%2F%2Fdeploy-preview-2791--gitpod-kumquat.netlify.app%2F&form_factor=desktop) on localhost?
Lighthouse report & [Netlify Report](https://app.netlify.com/teams/gitpod/builds/6331a2f6c67d3d0008114c15#L2813)
It was [93 in production](https://pagespeed.web.dev/report?url=https%3A%2F%2Fmain--gitpod-kumquat.netlify.app%2F&form_factor=desktop)


image

image

image

**Review by Cahllagerfeld — APPROVED** [review]
The changes look good to me 👍 Can we get it merged? @jacobparis

**Pull request merged**
