### PR TITLE
:rocket: Gitpod Community Heroes 🧡

### LINKED ISSUE #3180: Add community heroes's profiles to /community/heroes
Context: Requested improvement by @pawlean 

See [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=2625%3A396&t=8FXnUoRG4zCZ1vds-1)

**Next steps:**
- @pawlean could you share the heroes' profile images, usernames & names?
- how do you want to sort them? alphabetically or by the date of joining the heroes program?
- would you like to add a subheadline underneath "meet the heroes" saying how awesome they are? If yes, please suggest the wording
- technical implementation

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

[`/community/heroes#community-heroes`](https://deploy-preview-3479--gitpod-kumquat.netlify.app/community/heroes#community-heroes)

Review Points:

- [x] @pawlean, Pls check the community heroes data. & Names Sorting order (currently it is sorted Alphabetically, A->Z) - (looks good from my end).
- [x] @chrifro, design review (looks good from my end)

TODO:

- [x] Update Images of Community Heroes

## Related Issue(s)

Fixes #3180

## Release Notes

```release-note
Community Heroes List on Website Page: /community/heroes#community-heroes
```

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3479"></a>

### CODE REVIEW

**Comment by chrifro** [comment]
Nice thanks @Siddhant-K-code ✨

@pawlean the messaging and the links to Twitter are a bit contradicting. We ask them to get in contact on Discord but link to their Twitter or private websites. When creating the mockup, I expected to show the usernames for their Discord profiles. Could you either update the links or update the messaging?  

@Siddhant-K-code some profile images are cut. Could you scale them so that they always fill the circle?
Bildschirm­foto 2023-02-28 um 13 53 35
The gradient white should align with the background color (see [mockup](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/website?node-id=8632%3A16834&t=ie7f3pwqgX72RR5a-1))
Bildschirm­foto 2023-02-28 um 13 59 06

**Comment by Siddhant-K-code** [comment]
> @Siddhant-K-code some profile images are cut. Could you scale them so that they always fill the circle? - @chrifro 

Done 😄 

|Light Mode|Dark Mode|
|:---:|:---:|
|image|image|

**Comment by pawlean** [comment]
As the Heroes mostly in the Discord server (at least, most of the ones that we highlighted here) I say let's move to their Discord profiles. @Siddhant-K-code You can find their usernames [here](https://www.notion.so/gitpod/Community-Heroes-24785b33eb914b14a5ef141926151cdc?pvs=4#f0250aba22b44f1eb4bb32dc4f9e4de0).

**Comment by Siddhant-K-code** [comment]
Displaying a Discord username (because no URL exist based on a username) is less accessible/feasible for connection. I would suggest a standard twitter/mastodon username (but, maybe in a future)

**Comment by pawlean** [comment]
> Displaying a Discord username (because no URL exist based on a username) is less accessible/feasible for contact. I would suggest a standard Twitter/mastodon username (but, maybe in the future)

For a future iteration, we could have their social profiles instead. Not sure if this can be included in this PR? But if not, this looks good to me.

**Review by pawlean — APPROVED** [review]

**Pull request merged**
