### PR TITLE
[index] input add autoFocus + add galaxy bg to the prefix in the text.

### PR DESCRIPTION
**Pull request by nisarhassan12**
This PR address: https://github.com/gitpod-io/website/pull/331#pullrequestreview-333785251

### CODE REVIEW

**Comment by svenefftinge** [comment]
It now always jumps to the getting started section.

Also the `gitpod.io/#` is replaced with a slice of the galaxy bg.
Screenshot 2019-12-18 at 18 09 13

**Comment by nisarhassan12** [comment]
Thanks! This is what it looks like in Firefox:

image

I think I should make it my habit to always check on Chrome also.

**Comment by nisarhassan12** [comment]
I have fixed the issues.

**Comment by svenefftinge** [comment]
Thanks, Nisar. It doesn't set the focus but I think it's not so important.

**Pull request merged**
