### PR TITLE
add the new animations.

### LINKED ISSUE #2028: Replacing images with animation on the landing page
updating the images for sharing a workspace and multi-track development with animations.

You can find the new files [here](https://gitpod.slack.com/archives/C01KYFKAUQ4/p1651500448316269?thread_ts=1651252445.736659&cid=C01KYFKAUQ4)

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #2028 

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2041"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2041"></a>

### CODE REVIEW

**Comment by nisarhassan12** [comment]
@chrifro We will have to update the Share Workspace animation i.e currently if you look at the PR the animation starts when the element comes into the view and it pauses at the last frame but the issue with this animation is that the last frame is whitespace which results in nothing being displayed when the animation ends.

https://user-images.githubusercontent.com/46004116/168217992-9cf5cc71-f226-448b-82de-afdd62ad7a16.mov

**Comment by chrifro** [comment]
Yeah, that was exactly the worry that I mentioned before. And you can't cut the video in code right? e.g. make it stop at another frame?

**Comment by nisarhassan12** [comment]
@chrifro Yeah, I can't cut it in code but it can be done via Lottie Files I'm not sure what the exact workflow would look like I think you can cut it via Lottie files or first cut it with After Effects and then export the JSON from Lottie that can then be used on the website.

**Comment by nisarhassan12** [comment]
> @nisarhassan12 seems like it can be done in Lottie [[1](https://lottiefiles.com/blog/updates/introducing-the-lottie-editor)]. Can you see if you can fix it?

@chrifro I tried it and I'm unable to do it i.e when I upload the JSON there is no way for me to upload the image assets to the editor. 

image

**Pull request merged**
