### PR TITLE
Fix `.gitpod.yaml` -> `.gitpod.yml`

### PR DESCRIPTION
**Pull request by filiptronicek**
## Description

Unfortunately, we do not support our configuration files with the `.yaml` extension, and instead just `.yml`. This fixes occurrences of that in the repo.

[Code pointer](https://github.com/gitpod-io/gitpod/blob/4dadd7be619d2b741e02bbb18470c73a702e1269/components/gitpod-cli/pkg/utils/parseGitpodConfig.go#L16-L33)

## Release QA Checklist ✔️

<details>
  <summary>QA Checklist </summary>

## [Priority: High] Functional Testing

- [ ] Test all links to make sure they are working correctly
- [ ] Verify that all forms (sales, support, docs feedback)  are functioning properly and data is being captured correctly
- [ ] Check all buttons and calls-to-action to ensure they are leading to the correct pages
- [ ] Ensure that the website is mobile responsive and functions properly on different devices
- [ ] Ensure that page is optimal for Light/Dark Mode. ⇒ Text/Media Changes
  

## [Priority: High] Content Testing

- [ ] Check all website copies for accuracy and spelling/grammar errors
- [ ] Verify that all images and videos are displaying properly
- [ ] Ensure that all downloadable files are working correctly
- [ ] Check that all external links are functioning properly

## [Priority: Medium] Performance Testing

- [ ] Try to use optimal media assets. ([Decision Record - How To](https://github.com/gitpod-io/website/blob/main/docs/adr/0003-optimal-assets-format.md))
- [ ] Test website load times to ensure that the website is loading quickly
- [ ] Verify that the website can handle high traffic volumes without crashing
- [ ] Check that all website functionality is working properly under heavy load
- [ ] Perform cross-browser testing to ensure that the website works properly on all major browsers (Goolge Chrome, Firefox, Edge)

## [Priority: Medium] Accessibility Testing

- [ ] Ensure that the website meets basic accessibility guidelines.
- [ ] Test that users with disabilities can easily navigate and use the website
- [ ] Verify that all website content can be accessed using assistive technologies

By including these key items in your website release QA checklist, you can ensure that your website is fully functional, user-friendly, and meets your business requirements.

## Security Testing

> **Note**:💡 If we are changing something related to cookies or data storing or analytics side.

- [ ] Verify that the website is HTTPS secure and that there are no security vulnerabilities
- [ ] Ensure that all sensitive data is being stored and transmitted securely

  </details>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3683"></a>

### CODE REVIEW

**Review by Siddhant-K-code — APPROVED** [review]

**Comment by filiptronicek** [comment]
@Siddhant-K-code I wonder, is https://github.com/gitpod-io/website/pull/3683/commits/242be0e28c91e7e4037f4058202cbcab495ff5a1 necessary? I think it does not make any difference, the code blocks are still `yml` even on prod. 
image


I don't actually have problems with the change, but I think we should keep it for a separate PR, since it addresses something different.

**Comment by Siddhant-K-code** [comment]
> I think it does not make any difference, the code blocks are still yml even on prod.

Agree, Was just trying to make things consistent on raw files too & train the muscle memory to use `yml` if we copy-paste some of the bits. 

I am happy to revert[`242be0e`](https://github.com/gitpod-io/website/pull/3683/commits/242be0e28c91e7e4037f4058202cbcab495ff5a1), if you feel. Otherwise, it's good. WDYT?

**Comment by filiptronicek** [comment]
@Siddhant-K-code I think it would be best if we could split the PR and cherry-pick your changes onto a new one, could you do that? 🙏 

After that, we can merge this and continue there.

**Comment by Siddhant-K-code** [comment]
Raised #3692. Will merge this after CI checks

**Pull request merged**
