### PR TITLE
get started: add SaaS <> Self hosted toggle.

### PR DESCRIPTION
**Pull request by nisarhassan12**
This is how it looks: 

image

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1555"></a>

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/1555"></a>

### CODE REVIEW

**Comment by phimae** [comment]
Hey @nisarhassan12, thanks or the PR, a few comments:

- [ ] Include the link section below the clickable boxes (I've added another link to the features (e.g. the feature comparison part of the self hosted pricing page), see [Figma](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=1559%3A175) 
- [ ] Please make sure you use the latest logos for all (I think e.g. EKS logo is orange nowadays but please verify)
- [ ] Make sure the logos are all colorful, not just two of them (in the Figma file it is displaye to be colorful on hover but I think it's better if they are always colorful, otherwise it looks pretty sad)

Thanks!

**Comment by phimae** [comment]
@jakobhero, do we need to do anything to track interaction with this new element or is this automatically covered through the global even listener?

**Comment by nisarhassan12** [comment]
> - [ ] Make sure the logos are all colorful

@phimae I have asked Christin for the coloured versions of AKS and K3s logos will update the PR once I get them. 

>  it's better if they are always colorful, otherwise it looks pretty sad

cc @ChristinFrohne what do you think?  if we do it for these buttons then we should do it for the icons within the links in the "Launch an example workspace" section for consistency.

**Comment by ChristinFrohne** [comment]
Thanks @nisarhassan12 ✨

Some more comments:

- [ ] the buttons are 56px in height while the mockup suggests 48px. Any reasons why you changed that?

- [ ] can you align the grey button style to in the SaaS section as well? radius 16px, height 48px, text size 18px, shadow style

- [ ] the size of the logos isn't consistent. The Kubernetes logo is a lot bigger than GKE. In the mockup, I aligned all logos to have 22px in height.

- [ ] I will add the colored logos to the [component library](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=785%3A1456). You can then download them from there

>if we do it for these buttons then we should do it for the icons within the links in the "Launch an example workspace" section for consistency.

great catch on consistency, but I think it's fine here as we use colored icon buttons in the browser extension section as well. On the SaaS section, we decided to use a grey version as the section would be too colorful otherwise. That's not an issue here. The buttons are basically just two variants of the same button style.

**Comment by ChristinFrohne** [comment]
>Please make sure you use the latest logos for all (I think e.g. EKS logo is orange nowadays but please verify)

I noticed that on aws.amazon.com they use an orange version of the logo but I couldn't find a file to download it anywhere. [[1](https://aws.amazon.com/eks/)]. Not sure if the blue version is outdated but it's still commonly used everywhere [[1](https://www.google.com/search?q=amazon+eks&tbm=isch&hl=en-GB&chips=q:amazon+eks,online_chips:logo:cwXryTh45MM%3D&sa=X&ved=2ahUKEwiN-azFxNv1AhXQtKQKHY-ADzsQ4lYoAXoECAEQHg&biw=1211&bih=875)]

**Comment by jakobhero** [comment]
> do we need to do anything to track interaction with this new element or is this automatically covered through the global even listener?

unfortunately, clicking on the toggle was not automatically tracked as this is a new element i did not design the event listener for @phimae. i have added https://github.com/gitpod-io/website/pull/1555/commits/3cbbd58829c079e2accc3be4cc89a665a4b65699 to track the click on the element, let me know if you can think of any easier way to uniquely identify a toggle like this @nisarhassan12, happy to collaborate on this! (fyi: before targeting the `cursor-pointer`, i tried to track the `switch-container`, but this ended up firing two tracking events for each click.)

**Comment by nisarhassan12** [comment]
> - [x] the buttons are 56px in height while the mockup suggests 48px. Any reasons why you changed that?

Done ✅ Sorry I missed this earlier. 

> - [ ] can you align the grey button style to in the SaaS section as well? radius 16px, height 48px, text size 18px, shadow style

It would make more sense to do this as part of the creation of the component library where @Cahllagerfeld is working on the Button component at the moment. 

>  the size of the logos isn't consistent. The Kubernetes logo is a lot bigger than GKE. In the mockup, I aligned all logos to have 22px in height.

@ChristinFrohne I have now made the height and width to be consistent using tailwind values i.e 24px for the height and 32px for the width. Please note that we have `object-fit: contain` set on images to avoid this [see internal slack message](https://gitpod.slack.com/archives/C01KGM9ETU6/p1642584924030100) i.e it makes sure that icons and images preserve their original aspect ratio and don't become stretched setting 32px width does not mean that they will have this. Does this make sense? i.e if you look at the deploy preview the GKE logo will look the most wider although they all technically have the same width.

**Comment by nisarhassan12** [comment]
Thanks, @jakobhero for looking into it. 

Not sure whether it is a problem but we now have two toggles on the site with the same `data-analytics='{"label":"SaaS <> Self-hosted Toggle"}'` value i.e this newly added toggle in the Get Started section on `/` and the toggle on `/pricing` would not that make the tracking data less accurate or is it fine if two different pages have the same data-analytics values? 

> before targeting the cursor-pointer, i tried to track the switch-container, but this ended up firing two tracking events for each click.

Did you try tracking the event from the actual checkbox input? Let's maybe find some time tomorrow to collaborate on this.

**Comment by ChristinFrohne** [comment]
@nisarhassan12 I also just noticed that you used 18px font size for the footnote. Please stick to the mockup and consistency of the other view if there is no special reason to change it. The footnote should be 16px.

**Comment by nisarhassan12** [comment]
@ChristinFrohne @phimae Should we merge this now? 

@jakobhero we can look into the further tracking related stuff probably in a follow-up PR.

**Review by phimae — APPROVED** [review]
@nisarhassan12 @ChristinFrohne LGTM and can be merged. Let's discuss the tracking issue separately

**Pull request merged**
