### PR TITLE
3rd hierarchy to docs sidebar

### LINKED ISSUE #2221: Add 3rd hierarchy level to docs-sidebar
### Describe your feature

We should think about adding a third hierarchy level to our sidebar.

### User impact

Especially for reading the self-hosted docs, it would improve the logical structure of our documentation and increase the understandability.

### Additional context

This feature would not just be relevant for self-hosted, but also for IDEs for example: We would be able to group the Jetbrains and VS-Code-related Editors better inside the IDE's group for example; 

[See private Conversation in Slack](https://gitpod.slack.com/archives/C021JDXHXMF/p1654155840646119?thread_ts=1653566393.088229&cid=C021JDXHXMF)

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #2221

- [x] mobile Optimization
- [x] mobile styling
- [x] adding docs on how to create a third-level item
- [x] resolve merge conflicts
- [x] make badge addable to 3rd level item

Check the Third-Level item: https://deploy-preview-2260--gitpod-kumquat.netlify.app/docs/teams

Please don't merge this yet, we need to remove the dummy-files first

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2260"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2260"></a>

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
When adding a 3rd hierarchy level to the Docs, please consider the following things: 
- The subsection name needs to be defined in the 3rd level item AND in the parent item (technically a 2nd level item)
- The subsection name needs to be the slug, of the parent-item, e.g. `teams` in the example in this PR, because the parent-item has `teams` as the URL slug

**Comment by lucasvaltl** [comment]
Sure - do you want me to just add a change this PR?

**Comment by Cahllagerfeld** [comment]
Yep, exactly. Adding a 3rd level item, that's relevant for production as well :)

**Comment by lucasvaltl** [comment]
@Cahllagerfeld I tired to add a subsection called troubleshooting with two subitems (support patches and support bundles) - but it is not working. I tired to debug it but did not get far - could you check what I did wrong? Could have something to do with the fact that the self-hosted section is in its own folder and within a latest folder? Not sure.

**Comment by Cahllagerfeld** [comment]
I'll investigate 🕵️ 🔎

**Comment by lucasvaltl** [comment]
Seems like you fixed it - thank you!

**Comment by lucasvaltl** [comment]
Anything stopping us from merging this - apart from a review from an actual engineer ?😬 Anything I can help with?

**Comment by Cahllagerfeld** [comment]
I think we are good to go 👍 just reviewed it before lunch again and found a typo. Other than that, we should ship that 🛹

**Pull request merged**
