### PR TITLE
Strike initial release date for Jammy from January changelog

### PR DESCRIPTION
**Pull request by kylos101**
## Description

We'll share a separate changelog entry, with a new date, and comprehensive set of breaking changes.

## Related Issue(s)

Fixes # n/a
Related https://github.com/gitpod-io/website/pull/3490

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by Siddhant-K-code — COMMENTED** [review]
Thanks @kylos101 for this 🧡

Can we also add alternative date with striking the existing date?

**Comment by kylos101** [comment]
> Thanks @kylos101 for this orange_heart
> 
> Can we also add alternative date with striking the existing date?

We plan to do in a separate (newer) changelog entry for the date, this way it's easier to see / not buried in an old entry. I can go back and add it later once we know what it is.

I need to sync with @atduarte on that, it's supposed to be two weeks...but that's the offsite. :grimacing:

**Comment by kylos101** [comment]
> Thanks @kylos101 for this orange_heart
> 
> Can we also add alternative date with striking the existing date?

We plan to share in a new changelog entry (so it's easier for users to see, rather than find in an old entry). I'm not sure when that will be though and need to sync with @atduarte. 

Once we know, we can add for posterity in the January changelog, but it's less likely folks will see there.

**Comment by kylos101** [comment]
@Siddhant-K-code given [this](https://github.com/gitpod-io/website/pull/3533#issuecomment-1478863648), do you have any reservations about approving and merging this PR?

I'll share a draft changelog entry communicating the release for Jammy image support later today.

**Comment by kylos101** [comment]
@Siddhant-K-code for posterity, the changelog for updating to Jammy is located here.

**Comment by Siddhant-K-code** [comment]
Related #3544

**Review by Siddhant-K-code — APPROVED** [review]
I am merging this. We need to ship #3544 as soon as possible to avoid confusions to the users.

**Pull request merged**
