### PR TITLE
[WIP] Image optimizations

### PR DESCRIPTION
**Pull request by mikenikles**
Addresses #135 

`vite-imagetools` docs are in the repo's `next` branch at https://github.com/JonasKruckenberg/vite-imagetools/blob/next/docs/README.md

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/160"></a>

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/160"></a>

<a href="https://at-prebuild-page.staging.gitpod-dev.com/#https://github.com/gitpod-io/website/pull/160"></a>

### CODE REVIEW

**Comment by nisarhassan12** [comment]
I will take over this will hopefully start working on it from the next week. For some reason, I don't see any blur. 

https://user-images.githubusercontent.com/46004116/119221993-909a5580-bb0b-11eb-9951-2d6bc7d01124.mp4

**Comment by mikenikles** [comment]
Latest status for the `illustration-large.jpg` on the homepage:

|Before|After|
|--|--|
| image | image |

**Comment by mikenikles** [comment]
Blocked by https://github.com/matyunya/svelte-image/issues/109. We're putting this PR on hold and will also keep an eye on SvelteKit 1.0 and whether it provides support for image loading.

**Comment by mikenikles** [comment]
Cleaning up open & stale PRs. This one is tracked by #155.

**Pull request closed without merging**
