### PR TITLE
update the twitter preview to be our cubicle.

### LINKED ISSUE #374: Preview should be our cubicle
CleanShot 2021-04-15 at 11 28 26@2x

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #374 

Once this Pr is merged our preview on Twitter is gonna use the following cubicle image

image

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/502"></a>

### CODE REVIEW

**Comment by ChristinFrohne** [comment]
Can you add some padding around the image? According to the Twitter Card Validator, the graphic is partly cut and it'd look better with a bit more white space. Thanks
Bildschirmfoto 2021-05-28 um 09 33 41

**Comment by nisarhassan12** [comment]
Thanks, @ChristinFrohne I tried adding padding to the png preview image in Figma but I'm unable to do so. Can you add the padding to the above png image https://github.com/gitpod-io/website/pull/502#issue-655208133 ?

**Comment by ChristinFrohne** [comment]
Sure, I added it to the brand assets Figma file under Twitter assets/media image. If you want, you can also do adjustments yourself by resizing the frame 
Media image

**Comment by nisarhassan12** [comment]
Thanks, @ChristinFrohne I have updated the image.

**Comment by ChristinFrohne** [comment]
This is the result, when I test it:
Bildschirmfoto 2021-06-02 um 12 12 38

Please review again if everything is implemented correctly. If so, please merge it and test it yourself afterwards. The Twitter card previewer might have a problem with the preview link. 
https://cards-dev.twitter.com/validator

**Comment by nisarhassan12** [comment]
I just merged the Pr and tested it and it seems to work perfectly. 
image

**Pull request merged**
