### PR TITLE
chore: Refactor `types` definition

### LINKED ISSUE #1543: Convert `src/lib/types/*` to actual `*.d.ts` files

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
Signed-off-by: Siddhant Khare <siddhant@gitpod.io>

fixes #1543

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2839"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2839"></a>

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
I have to admit, I don't know the impact of that change. I was wondering if we need the `declare` keyword in declaration files. Do you know anything more about this?

**Comment by Siddhant-K-code** [comment]
> I have to admit, I don't know the impact of that change. I was wondering if we need the `declare` keyword in declaration files. Do you know anything more about this?

Oh yeah, I totally missed that. using `declare` is a good thing, when we have `*.d.ts` files. Even though it works with export. But `declare` is a good principle to use. I will make that changes

**Comment by Cahllagerfeld** [comment]
As I said, I can't really tell you anything about that change. If you feel confident about it, go for it and merge it!

**Comment by Siddhant-K-code** [comment]
> As I said, I can't really tell you anything about that change. If you feel confident about it, go for it and merge it!

Let me test the Feedback and other integrations (need help in sales, it would be good that this time you can tell me the process where to see these contact mails) and then I will merge it tomorrow morning (my time)

**Comment by Siddhant-K-code** [comment]
For now Merging this, will revert in case anything breaks.

**Comment by Siddhant-K-code** [comment]
Improvements: 
image

**Pull request merged**
