### PR TITLE
[TrustedBy] enable horizontal scrolling.

### PR DESCRIPTION
**Pull request by nisarhassan12**
This is how it looks:

image

Fixes gitpod-io/website#600

### CODE REVIEW

**Comment by ChristinFrohne** [comment]
The scrolling bar that you have on your screenshot and the one I get on my mac look nice. But on my windows it doesn't look that good. It quite massive. Can that be adjusted? 

Annotation 2020-04-30 082839

Also could you even out the spacing between the logos? There is a lot more space before "openAI" than before "d-wave". Maybe then it's also possible to not have the "openai" logo cut

**Comment by nisarhassan12** [comment]
> Also could you even out the spacing between the logos? There is a lot more space before "openAI" than before "d-wave". Maybe then it's also possible to not have the "openai" logo cut

It's quite hard to do as they are not equal in width and a few of them have whitespace in them on either side see the `Uber` logo below: 

image

I have reduced there width this is how they look now.

image

**Comment by ChristinFrohne** [comment]
The spacing is better now, it's great that the logo isn't cut anymore. But I agree with Sven that the scrolling bar looks weird, especially on windows. Do you have another idea to visualize the scrolling @nisarhassan12 ? Otherwise, we can just stick with the arrow in the way we currently have it

**Comment by svenefftinge** [comment]
Or two rows and make the logos a tad smaller?

**Comment by ChristinFrohne** [comment]
I find two rows of logos on the start screen rather noisy. Another solution could be this:
Bildschirmfoto 2020-05-06 um 12 24 07

It swipes through the logos automatically and you can also click through it via the dots. Here we could arrange 3 sets of 5 logos each and swipe through them.
https://buddy.works/on-premises

**Comment by nisarhassan12** [comment]
> I find two rows of logos on the start screen rather noisy. Another solution could be this:
> Bildschirmfoto 2020-05-06 um 12 24 07
> 
> It swipes through the logos automatically and you can also click through it via the dots. Here we could arrange 3 sets of 5 logos each and swipe through them.
> https://buddy.works/on-premises

Thanks @ChristinFrohne It looks nice but it can be problematic to use on mobile devices i.e the tap targets are gonna be too small.

**Comment by ChristinFrohne** [comment]
Have you checked their mobile view? They use it anyway.
Maybe we could enable finger swiping on mobile instead of clicking on the dots.

**Comment by nisarhassan12** [comment]
Thanks.Swiping would make sense. thanks.

**Pull request closed without merging**
