### PR TITLE
housekeeping: /for/opensource

### PR DESCRIPTION
**Pull request by ghuntley**
## Description

Last-minute touchups to /for/opensource

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/1380"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1380"></a>

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Todo for myself (feedback from Christin):

- [ ] The logo that belongs to the quote should always be black. Currently they are all grey by default. Can you make the RedwoodJS logo the first one and display that quote by default? 

image

**Comment by Siddhant-K-code** [comment]
> The logo that belongs to the quote should always be black. Currently they are all grey by default. Can you make the RedwoodJS logo the first one and display that quote by default?

I can work upon this!

**Comment by ghuntley** [comment]
Have reworked this pull request after the tailwind migration. Requires re-review and 👀 from a design perspective.

**Review by ChristinFrohne — COMMENTED** [review]
Awesome to see this come alive again 🥳 and welcome back @ghuntley 👋

Some comments:

- [ ] can you find an image that rather describes the company or the vision of the company than the author's profile picture?

- [ ] the image can also be smaller on mobile (see [mockup](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=521%3A2139))

- [ ] decrease width of the bullet points to 638px (see [component library](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=554%3A1898))
- [ ] shorten the text under "actions speak louder than words" to two lines. E.g. move "acknowledging and supporting the maintainers" to the headline.

- [ ] improve design of the last card: increase text width to 510px (see [component](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=514%3A2831)), shorten bold text to max two lines.

- [ ] mobile view: check the text breakpoints so there a no single words in a row. E.g. "Open source is in our DNA"

Otherwise it looks good to me 🙂

**Comment by ghuntley** [comment]
> * [ ]  can you find an image that rather describes the company or the vision of the company than the author's profile picture?

Preference is to showcase people behind the open-source projects and helps avoid the pitfall that majority of open-source projects do not have logos.

**Comment by Cahllagerfeld** [comment]
>  mobile view: check the text breakpoints so there a no single words in a row. E.g. "Open source is in our DNA" 

I'm not sure if this is achievable because its heavily depending on the actual device the user is having.

A possible solution is lowering the font-size, but this would lead to inconsistencies and wouldn't make sure, that this problem won't occur.  There will always be like a breakpoint where the content breaks, or do you have any idea how to achieve this @mikenikles ?

**Comment by nisarhassan12** [comment]
@Cahllagerfeld You can use the `&nbsp;` HTML character entity between the last two words i.e 
```
"Open source is in our&nbsp;DNA"
```
 and then use `{@html text}` to render the string.

**Comment by Cahllagerfeld** [comment]
> > * [ ]   can you find an image that rather describes the company or the vision of the company than the author's profile picture?
> 
> Preference is to showcase people behind the open-source projects and it helps avoid the pitfall that majority of open-source projects do not have logos.

Is this ready for review, or do we need to take further action here? @ghuntley

**Comment by ghuntley** [comment]
Once merge conflicts are resolved, need someone to review / green tick then I'll just a hyperlink or two to the application form then self-merge.

**Pull request merged**
