### PR TITLE
[Nav] add login button to the side of the hamburger on mobile. 

### PR DESCRIPTION
**Pull request by nisarhassan12**
This is how it looks: 
image

### CODE REVIEW

**Comment by AlexTugarev** [comment]
Screen Shot 2020-02-20 at 13 48 36

vertical alignment is not like above for me (chrome on mac)



if need a second click to open the menu now

**Comment by jankeromnes** [comment]
Actually, I can reproduce the "two taps needed to open the menu", but that issue is actually also present on www.gitpod.io -- so it's not related to this PR (but should probably be fixed too).

**Comment by nisarhassan12** [comment]
The alignment is now fixed 
image

**Comment by jankeromnes** [comment]
Quick note in passing (this also pre-dates your PR, so feel free to fix this in another PR), you may notice that some parts of the cookie prompt are still visible on the bottom corners of the mobile menu.

This is more visible on larger screens:

Screenshot 2020-02-20 at 15 58 17

Would be cool to fix this too. Not urgent though. 😊 Feel free to merge this first.

**Comment by jankeromnes** [comment]
And another FYI, the `Solutions` and `Resources` collapsed sections seem to suffer from the same `onFocus` problem, requiring two taps to open them. Also not urgent though. 😄

**Pull request merged**
