### PR TITLE
fix: nav-bar menu  design

### LINKED ISSUE #3211: improve menu drop down style for dark theme
|status quo| new style|
|-|-|
|Bildschirmfoto 2023-01-02 um 09 49 08|Bildschirmfoto 2023-01-02 um 09 49 19|

Changes (only apply to dark mode):
- change bottom stroke color to #12100C
- add dark theme box-shadow

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

New [Preview](https://deploy-preview-3251--gitpod-kumquat.netlify.app/) => 

image

## Related Issue(s)

Fixes #3211

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3251"></a>

### CODE REVIEW

**Review by chrifro — COMMENTED** [review]
The bottom stroke of the drop-down is still there
Bildschirm­foto 2023-01-16 um 14 05 27

In the issue, I suggest changing the bottom stroke color to #12100C. How come you decided not to implement that? #3211

**Comment by Siddhant-K-code** [comment]
Resolved ✅ 

image

**Comment by Siddhant-K-code** [comment]
It broke the whole dividers, let me fix it ⚠️

**Review by chrifro — COMMENTED** [review]
The box shadow still doesn't align with [the mockup ](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=556%3A4656&t=u7FUDQ2jMh9nPjlp-1). In the mockup it's the following:
Bildschirm­foto 2023-01-17 um 10 42 00

How come you decided to use a different shadow style? Currently, the drop-down doesn't distinguish enough from the background. A bigger shadow would help with that.

Feel free to merge the PR once this has been addressed

**Pull request merged**
