### PR TITLE
fix: remove newsletter signup

### LINKED ISSUE #941: Delete newsletter signup from /blog
We need to be more specific with our newsletter sign-up widget. Right now it’s uncertain which email settings are affected by it. To clarify when it relates to changelog emails and when to the devx digest, we should delete it from /blog

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #941 

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/950"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/950"></a>

### CODE REVIEW

**Comment by mikenikles** [comment]
Let's also remove it from the individual blog pages please.

**Comment by Cahllagerfeld** [comment]
Do you mean the the Signup from [this](https://github.com/gitpod-io/website/tree/main/src/components/blog) folder?

**Comment by mikenikles** [comment]
Yes, in particular [this `:else` block](https://github.com/gitpod-io/website/blob/main/src/components/blog/blog-content-layout.svelte#L24).

The `blog-content-layout.svelte` component wraps each individual blog post, but also DevX Digest newsletter editions. For DevX Digest posts, we have a separate header that includes the newsletter signup form and we want to keep that.

**Comment by Cahllagerfeld** [comment]
Okay sure, I didn't realize that to be honest 😅 I'll update the PR tomorrow (:

**Comment by Cahllagerfeld** [comment]
Hi Mike 😄 
are the changes fine, or do I have to do other adjustments as well? (:

**Review by mikenikles — APPROVED** [review]
Awesome, thanks for the additional update.

**Comment by Cahllagerfeld** [comment]
You're welcome 👍

**Pull request merged**
