### PR TITLE
[blog]: Gitpod Core Values.

### PR DESCRIPTION
**Pull request by nisarhassan12**

### CODE REVIEW

**Comment by phimae** [comment]
Thanks for the quick turnaround @nisarhassan12! I did some formatting changes myself but there are a few things where I'd need your help:

- [ ] Change the quote of our purpose to look like the ones we use in the case studies ( I tried with `>` but it references another style)
image
- [ ] Header image should not be cut off on the sides on mobile
image

Thanks!

**Comment by phimae** [comment]
@nisarhassan12 once you finished the above to-dos, please still do not merge until @JohannesLandgraf reviewed

**Comment by nisarhassan12** [comment]
ok, @phimae sounds good.

**Comment by nisarhassan12** [comment]
> - [ ] Header image should not be cut off on the sides on mobile

@chrifro Please provide a mobile version of the image atm I'm using the same for both mobile and desktop.

**Comment by chrifro** [comment]
@nisarhassan12 here is the mobile version:
Blog image (1) (1)
https://www.figma.com/file/gq1v6dj0rzs4tvJcFabKPy/Blog-%26-Changelog-images?node-id=545%3A39

**Comment by phimae** [comment]
Now that the videos are complete, we can ship this blog post. A few changes need to be done: cc/ @nisarhassan12 @chrifro 

- [ ] Use updated text from [here](https://docs.google.com/document/d/1a_a0QJskxvXn2S6H6FlO6Uq8PTmrrVDaLJVxi3YLKzw/edit)
- [ ] Include section header images with each core value similar to how we have done it [here]([https://www.gitpod.io/blog/next-chapter-for-Gitpod](https://www.google.com/url?q=https://www.gitpod.io/blog/next-chapter-for-Gitpod&sa=D&source=docs&ust=1653040607630077&usg=AOvVaw1xlCHffyd62DrD1LGwVmLN)) 
image
- [ ] embed the [highlights offsite video](https://drive.google.com/file/d/1Al5f6EnesecGpvc8HseFB2hE9mw99Bbm/view?usp=sharing) in the end of the blog post
- [ ] change the date to be more current

Sync with @JohannesLandgraf on when and how to launch (since I will be OOO until June 6)

Thanks!!

**Comment by chrifro** [comment]
>embed the [highlights offsite video](https://drive.google.com/file/d/1Al5f6EnesecGpvc8HseFB2hE9mw99Bbm/view?usp=sharing) in the end of the blog post

I talked with Johannes and there will be another loop on this video. I will let you know once we have the final video (hoping by EOD today)

Thanks for the update. Have a great vacation! 🏝

**Comment by chrifro** [comment]
**Outstanding to-dos:**

- [ ] update preview and header image on mobile and desktop. See [mockup](https://www.figma.com/file/gq1v6dj0rzs4tvJcFabKPy/Blog-%26-Changelog-images?node-id=531%3A35)

- [ ] embed this YouTube video https://youtu.be/IMpl5dtWIlU. And make sure the preview image is shown

- [ ] change the date to today
- [ ] ask Johannes to review the PR before publishing it [[1](https://github.com/gitpod-io/website/pull/1847#issuecomment-1087246065)]

@Cahllagerfeld could you help out with the outstanding to-do's as Nisar is OOO? 🙏

**Comment by chrifro** [comment]
>please still do not merge until @JohannesLandgraf reviewed [[1](https://github.com/gitpod-io/website/pull/1847#issuecomment-1087246065)]

@JohannesLandgraf could you review it? 🙏 

**Note:** The tweets are already scheduled for 16:30 CEST today, we'd need to have the blog post live by then.

**Comment by chrifro** [comment]
Thanks!

>One thing that I noticed is that we use the same background for the last two blog entries maybe we want to change on cover picture cc @chrifro

I noticed that as well. But the light kumquat fits best for the topic and with the contrast to all the icons. 

I'd say let's keep it as it is and I'll watch out that the background color for the next image differs.

**Pull request merged**
