### PR TITLE
[contributing] init

### PR DESCRIPTION
**Pull request by Kreyren**
This is to make merge requests alike https://github.com/gitpod-io/website/pull/464#pullrequestreview-353693715 faster to process

### CODE REVIEW

**Comment by Kreyren** [comment]
>  think that the commit message structure is not important enough to be specified in it.

It was required on https://github.com/gitpod-io/website/pull/464#pullrequestreview-353693715 so i believe that it is important

> even in this project, different developers use different commit message formats. 

Proposing the winehq format which has been adapted in linux which is

```
component: summary

Description

Signature
```

> I personally prefer the [docs] prefix

Assuming the example above this adds two additional characters that would make github/gitlab, etc.. cut whole word in the summary so i believe that proposed is better for website search

> I don't want to make this a strict rule.

Why not assuming that it makes it easier to search the commits for possible regression?

> The squashing of commits is a good idea, but then again it's also pretty easy to accept a PR with hundreds of commits by using GitHub's Squash & Merge button.

I'm also agains squashing commits by contributor since this hides helpful changes and avoids commit spam in case there are more changes assuming that commit contains a message that causes the commit to be references elsewhere.

**Comment by svenefftinge** [comment]
I agree with Jan, that adding requirements doesn't feel encouraging.
How about using a more welcoming tone that suggests rather than expects?

**Comment by Kreyren** [comment]
I'm not sure how to phrase it in such a way that would be more friendlier without causing entropy in commits.

**Comment by ret394** [comment]
>I don't want to make this a strict rule.

sane, polite, friction less defaults.

thanks. have a nice day. keep up the great work. 👏
thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)

**Comment by Kreyren** [comment]
@ret394 what

**Comment by jankeromnes** [comment]
Thanks again for proposing a `CONTRIBUTING.md` file!

Unfortunately, the proposed content doesn't make sense, because commits messages are allowed to have any format (see https://github.com/gitpod-io/website/commits/master). Also, while squashing commits is nice, it is also not a requirement, because the PR can easily be "squashed & merged" by GitHub.

So I'll close this for now.

**Pull request closed without merging**
