### PR TITLE
Clean up code style & remove card backgrounds

### PR DESCRIPTION
**Pull request by jwpjrdev**
The current site shows a very broken looking set of cards:

They’re right next to each other and their heights aren’t the same. I personally despise it.

This PR does two things:
1) it cleans up some of the code style in the file to be more consistent
2) it removes the card’s backgrounds. I think this look better because it breaks up the content-in-a-card style of the page.

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/896"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/896"></a>

### CODE REVIEW

**Comment by jwpjrdev** [comment]
Actually one thing I seem to have neglected is that when I was experimenting with one big card that encompassed the two I left the card-left and card-right classes assigned to the respective div elements even after the classes were removed from the final result. In theory you can remove card-left and card-right from the classes altogether but it should be tested first. I'll give it a try once I'm back on my iPad with Wi-Fi.

**Comment by jwpjrdev** [comment]
I added another commit to remove the unused classes.

**Comment by jwpjrdev** [comment]
I just took another look at it and the left card is higher than the right card. I assume this is because of flex.

**Comment by nisarhassan12** [comment]
> I just took another look at it and the left card is higher than the right card. I assume this is because of flex.

Thanks. I also had a look and what you told me is the case. I would personally prefer to have the white background being put on again as that is probably what we have in the mockup and rather make their height equal.

Screen Shot 2021-08-30 at 12 02 49 AM

**Comment by jwpjrdev** [comment]
I'll take a look at it tomorrow. I'm not too familiar with the codebase so I'll have to dig around a bit first but I'll see what I can do.

**Comment by nisarhassan12** [comment]
@jwpjrdev Are you still interested in further looking into it ? If you don't have the time and availability the I can take over this if you like ? Thanks

**Comment by jwpjrdev** [comment]
That would be great! I've been busy with schoolwork this past week or so.

**Comment by nisarhassan12** [comment]
@mikenikles @ChristinFrohne I have made the remaining changes this is how it looks now: 

image

**Comment by jwpjrdev** [comment]
Looks great!

**Comment by jwpjrdev** [comment]
I'll spin up a workspace and see how it looks on my iPad in a sec

**Comment by ChristinFrohne** [comment]
Cool, thanks. As far as I can see this change stocks the boxes above each other instead of squeezing them next to each other, correct? LGTM
|before |after|
|-|-|
|Bildschirmfoto 2021-09-20 um 09 00 59|Bildschirmfoto 2021-09-20 um 09 00 51|

**Review by ChristinFrohne — APPROVED** [review]

**Comment by nisarhassan12** [comment]
>  As far as I can see this change stocks the boxes above each other instead of squeezing them next to each other, correct?
Yep. On a specific breakpoint under the desktop one.

**Pull request merged**
