### PR TITLE
update the style guide pdf.

### PR DESCRIPTION
**Pull request by nisarhassan12**
<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/486"></a>

### CODE REVIEW

**Review by ChristinFrohne — APPROVED** [review]
It takes quite a long time to load the page. Any idea how to reduce the loading time?

**Comment by nisarhassan12** [comment]
You meant https://www.gitpod.io/assets/style-guide.pdf right that is because it is not a webpage but instead a pdf and in order for the browser to show the PDF, the browser has to first download the file which nearly 20 MB which is a lot a solution would be to create a page for style guide like the media kit itself.

**Comment by ChristinFrohne** [comment]
>You meant https://www.gitpod.io/assets/style-guide.pdf right? that is because it is not a webpage but instead a pdf and in order for the browser to show the PDF, the browser has to first download the file which nearly 20 MB which is a lot a solution would be to create a page for style guide like the media kit itself.

Can we not reduce the size of the pdf?

**Comment by nisarhassan12** [comment]
Thanks. @ChristinFrohne great suggestion The PDF file is now 98% smaller thanks to https://www.ilovepdf.com/ I have made this PR for it https://github.com/gitpod-io/website/pull/491/files

**Pull request merged**
