### PR TITLE
[screencasts] Add link to top-level menu

### PR DESCRIPTION
**Pull request by jankeromnes**

### CODE REVIEW

**Comment by jankeromnes** [comment]
Seems to look good on all relevant screen sizes:

### Desktop

Screenshot 2021-01-22 at 14 32 46

### iPad (landsape)

Screenshot 2021-01-22 at 14 33 09

### iPhone Plus (portrait)

Screenshot 2021-01-22 at 14 33 35

**Comment by gtsiolis** [comment]
Thanks for adding this @jankeromnes!

**issue**: This will not behave well on the `/docs`, right?

**Comment by jankeromnes** [comment]
@gtsiolis You mean this?

Screenshot 2021-01-22 at 14 44 29

**Comment by gtsiolis** [comment]
Yes @jankeromnes! If you want to add this as is, let's also changed the margin below to `4rem` to avoid introducing the overflow. WDYT?

https://github.com/gitpod-io/website/blob/5567266c39f93cdc056950bbfb50407d4c5dc0c7/src/components/Nav.tsx#L72

**Comment by jankeromnes** [comment]
@gtsiolis Great suggestion! Many thanks, looks indeed better with `4rem`:

Screenshot 2021-01-22 at 14 59 07

**Comment by jankeromnes** [comment]
A potential follow-up that was suggested: Removing the "Blog" top-level menu link & reverting back to `5rem` margins.

(I'm personally a bit hesitant on this, since the Blog seems important to me, so I'll leave this change to a potential follow-up PR 😇 🚀)

**Pull request merged**
