### PR TITLE
[PricingBox] add the missing tick icon to the list items.

### PR DESCRIPTION
**Pull request by nisarhassan12**
This is how it looks: 
image

### CODE REVIEW

**Comment by ChristinFrohne** [comment]
Please make sure that the list of features is arranged in the middle of each box. 

Bildschirmfoto 2020-02-25 um 16 47 00

**Comment by nisarhassan12** [comment]
I have made the changes please have a look again.

**Comment by ChristinFrohne** [comment]
Please use the full width for the boxes. Currently, there is a small gab. Can you make the boxes a bit wider instead? 

Besides that everything looks good 
 Bildschirmfoto 2020-02-26 um 07 30 46

**Comment by nisarhassan12** [comment]
Thanks! great Catch! I have fixed this.

**Pull request merged**
