### PR TITLE
add canonical urls.

### LINKED ISSUE #661: [seo]: The site is missing the canonical urls.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #661

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/667"></a>

### CODE REVIEW

**Comment by nisarhassan12** [comment]
@mikenikles @jankeromnes Do we need a trailing slash at the end of the URLs or is that fine if we leave it ? 

I see www.gatsbyjs.com using a trailing slash at the end of all the canonical URLs. 

<link rel="canonical" href="https://www.gatsbyjs.com/" data-baseprotocol="https:" data-basehost="www.gatsbyjs.com">

**Comment by mikenikles** [comment]
Please see my comment at https://github.com/gitpod-io/website/issues/552#issuecomment-855060587.

**Comment by nisarhassan12** [comment]
Thanks. Your comment means no trailing slash. Can we merge this now ?

**Comment by mikenikles** [comment]
I labelled this as `on-hold` until SvelteKit 1.0 is released. Please see the link I posted on Jun 22 above for details.

Once we migrate, we will enforce no trailing slashes.

**Comment by mikenikles** [comment]
Cleaning up open & stale PRs. We'll continue to track this in #661.

**Pull request closed without merging**
