### PR TITLE
Align Ready-to-Code graphics.

### LINKED ISSUE #412: Align graphics
On the front page the graphics should be properly aligned with the buttons on the left.

Currently it looks like that.

Screenshot 2020-01-21 at 09 13 26

Also the horizontal alignment looks arbitrary.

### PR DESCRIPTION
**Pull request by jbicker**
Fixes #412

### CODE REVIEW

**Comment by ChristinFrohne** [comment]
Can you give the hover-buttons the same height as the boxes of the graphic?

**Comment by nisarhassan12** [comment]
@ChristinFrohne  I have made the change please have a look again :)

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made the change please have a look again :)

**Comment by ChristinFrohne** [comment]
So you can't make the buttons a bit bigger, so they are aligned with the graphic right? 
If that's not possible, it's fine like this

**Comment by nisarhassan12** [comment]
> So you can't make the buttons a bit bigger, so they are aligned with the graphic right?
> If that's not possible, it's fine like this

It can be possible but only for a single breakpoint i think.

**Pull request merged**
