### PR TITLE
Fixed.  Image overlapping text issue:- Docs: **Getting Started**

### LINKED ISSUE #268: Docs: **Getting Started** . Image is overlapping text.
Currently, A Image in Docs: https://www.gitpod.io/docs/10_getting_started/ is overlapping the text. 

image

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #268 .
This is what it looks like now:

image

### CODE REVIEW

**Comment by svenefftinge** [comment]
@nisarhassan12 Thanks for taking care if this. It's great you are doing these kind of things on your own. I wonder however if this should not be generally taken care of in CSS. Couldn't this possibly happen in other places as well?

**Comment by svenefftinge** [comment]
Maybe we can put some space below all all images. E.g. on this page the screenshots sit close to the text below as well https://www.gitpod.io/docs/54_git/

**Comment by nisarhassan12** [comment]
Thanks! agree! We should make this change globally through out the `docs.

**Comment by nisarhassan12** [comment]
Thanks! @svenefftinge I have made the change globally this is what it looks like: 

image

**Pull request merged**
