### PR TITLE
Remove duplicate organization member permission

### PR DESCRIPTION
**Pull request by gtsiolis**
## Description

Update organizations roles as org members can no longer add projects.

See [relevant discussion](https://gitpod.slack.com/archives/C01KGM9DVRC/p1678811492640669?thread_ts=1678811014.293419&cid=C01KGM9DVRC) (internal).

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3515"></a>

### CODE REVIEW

**Review by Siddhant-K-code — COMMENTED** [review]
Being a member, I can still able to "Add Projects". See this [internal conversation](https://gitpod.slack.com/archives/C01KGM9DVRC/p1678855338312729?thread_ts=1678811014.293419&cid=C01KGM9DVRC)

**Comment by gtsiolis** [comment]
You're right, @Siddhant-K-code! Re-posting from the [relevant discussion](https://gitpod.slack.com/archives/C01KGM9DVRC/p1678873612212039?thread_ts=1678811014.293419&cid=C01KGM9DVRC) (internal):

> I subconsciously opened https://github.com/gitpod-io/website/pull/3515 even though I said I'd not. Let me re-purpose that PR. 

Updated the PR to simply remove the duplicate entry in the roles table.

**Review by Siddhant-K-code — APPROVED** [review]
Thanks 🧡 

@gtsiolis Can you please update PR Title & Description before merging 🙏🏽

**Comment by gtsiolis** [comment]
@Siddhant-K-code DONE

**Pull request merged**
