### PR TITLE
add composer info

### PR DESCRIPTION
**Pull request by shyim**
## Description
Adds info about how to configure composer

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2891"></a>

### CODE REVIEW

**Review by Siddhant-K-code — APPROVED** [review]

**Comment by Siddhant-K-code** [comment]
Thanks, @shyim for the contribution ✨ 

Looping in @meysholdt for CLA Signing 🙌🏼

**Comment by Siddhant-K-code** [comment]
> wtfff for a simple docs change a cla sign with address and co 🤣

CLA is not limited to the type of change/ no. of lines changed. It is a required process to accept your proposed changes. 🙏🏼

**Comment by shyim** [comment]
it is signed

**Comment by meysholdt** [comment]
Thank you for signing the CLA, @shyim!

**Pull request merged**
