### PR TITLE
[docs] Add LaTeX in Gitpod tutorial based on https://github.com/ptrottier/latex

### PR DESCRIPTION
**Pull request by jankeromnes**

### CODE REVIEW

**Comment by PTrottier** [comment]
I love it, thanks @jankeromnes!

**Comment by PTrottier** [comment]
> What about VSCode extensions (keep the guides consistent)
> [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop)
> [LaTeX Snippets](https://marketplace.visualstudio.com/items?itemName=JeffersonQin.latex-snippets-jeff)

Wow, thanks for sharing, those looks really powerful!

**Comment by JesterOrNot** [comment]
@jankeromnes are you still working on this?

**Comment by jankeromnes** [comment]
Many thanks for the reviews! I've added the recommended extensions, and the guide looks good to me now.

Merging as is, but please feel free to suggest any changes to it in follow-up Pull Requests. 🙂

Thanks again @PTrottier for prompting this super cool addition to our docs!

**Pull request merged**
