### PR TITLE
[docs] theia configuration

### PR DESCRIPTION
**Pull request by Kreyren**
Fixes: https://github.com/gitpod-io/gitpod/issues/1279

@felipecassiors: Feedback is appreciated :)

### CODE REVIEW

**Comment by felipecassiors** [comment]
I think this should be included in the left panel, and in [this file](https://github.com/gitpod-io/website/blob/master/src/docs/configuration.md).

Left panel I mentioned:
image
https://www.gitpod.io/docs/

**Comment by Kreyren** [comment]
@felipecassiors Thanks for reminder! Forgot about it >.>

**Comment by Kreyren** [comment]
DO_NOT_MERGE: The readme file needs to be excluded from the page build

**Comment by Kreyren** [comment]
### SECURITY NOTICE
```
found 10 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by Kreyren** [comment]
CI fails for https://github.com/gitpod-io/website/pull/512/commits/0382ca746baf10823ba2faef71836097c4ce9e8b which i assume is CI failure caused by a `System Error` ?

Seems to build on my end

**Pull request merged**
