### PR TITLE
New Brand logos

### LINKED ISSUE #3667: Update Logos on Animation Logo & Other components
> Related #3664 & https://github.com/gitpod-io/website/pull/3664#issuecomment-1558550796 for more context, ongoing decisions 

Component that needs to be updated: 
- [Used by Component](https://github.com/gitpod-io/website/blob/main/src/lib/components/index/used-by.svelte)
- [Animated Logos](https://github.com/gitpod-io/website/blob/19736673d361d1fc37137533c4642935976752eb/src/lib/components/animated-logos.svelte)

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Related Issue(s)

Fixes #3667

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3670"></a>

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
Need review on the order of the Logos (cc: @taliamoyal): 

image

**Comment by taliamoyal** [comment]
This looks good to me!

**Comment by Siddhant-K-code** [comment]
> Feels a bit inconsistent

Ahh! agree with this. wdyt @taliamoyal?

**Comment by taliamoyal** [comment]
Defer to @chrifro!

**Pull request merged**
