### PR TITLE
[newsletter]: Make sure no one signup twice.

### LINKED ISSUE #833: [newsletter]: make sure no one can signup twice.
Currently, there are duplicate emails in the sheet because people signed up multiple times.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #833

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/835"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/835"></a>

### CODE REVIEW

**Review by ChristinFrohne — COMMENTED** [review]
- [x] The size of the box is changing when submitting the email. 

https://user-images.githubusercontent.com/46345125/129174770-980e1ea4-5234-43e8-b262-63006a3c8d01.mov


- [ ] can you replace "stay updated" with "You are already signed up" and add "Lean back and relax. The next newsletter will be sent right to your inbox." to the text field?

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made the requested changes please have a look again.

**Comment by nisarhassan12** [comment]
@ChristinFrohne @mikenikles  I'm merging this Pr now Please comment here if you have any further feedback or things to be addressed.

**Comment by ChristinFrohne** [comment]
looks good. Please clean up the exiting spreadsheet as well. Some emails are listed several times @nisarhassan12

**Comment by nisarhassan12** [comment]
I have removed the duplicates from the sheet.

**Pull request merged**
