### PR TITLE
V2 : In Progress

### PR DESCRIPTION
**Pull request by nisarhassan12**

### CODE REVIEW

**Comment by svenefftinge** [comment]
Hey Nisar! This looks better and better ❤️
I noticed a blink of an eye glitch, when the menu changes to burger-mode.

**Comment by nisarhassan12** [comment]
> Hey Nisar! This looks better and better heart
> I noticed a blink of an eye glitch, when the menu changes to burger-mode.

Thanks, @svenefftinge I think that's because of the animation. Should I remove the animation :slightly_smiling_face:?

**Comment by nisarhassan12** [comment]
@svenefftinge I have updated the animation. Does it look any better now ?

**Comment by svenefftinge** [comment]
no, it's still there on chrome.

menu-glitch

**Comment by svenefftinge** [comment]
I'd generally be in favor of reducing the amount of animations / speeding them up a bit.

**Comment by svenefftinge** [comment]
The text needs some space.
Screenshot 2019-12-05 at 09 25 40

**Comment by nisarhassan12** [comment]
> I'd generally be in favor of reducing the amount of animations / speeding them up a bit.

Thanks! I have removed the Nav Animation and the eye-glitch issue is now fixed :slightly_smiling_face:

**Pull request closed without merging**
