### PR TITLE
improve the top navigation.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #2413 

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2420"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2420"></a>

### CODE REVIEW

**Comment by chrifro** [comment]
The desktop view looks great, for the mobile view there are several things to adjust:

- [ ] resources should be bold when and black when it's active. All other items are grey (on hover they turn black)
- [ ] the hover color is sand light (just like on desktop) 
- [ ] first comes the "get a demo" button followed by the "login"
- [ ] the position of the contact widget is off

|mockup|production|
|-|-|
|Bildschirmfoto 2022-07-15 um 15 29 27|Bildschirmfoto 2022-07-15 um 15 28 23
|

**Comment by chrifro** [comment]
@jacobparis could you review the messaging of the sub-items? 🙏

**Comment by nisarhassan12** [comment]
>  - [ ] the position of the contact widget is off

@chrifro I looked into fixing it but was not able to do so, so I have opened this follow-up issue #2440 for this will try to fix this later on, I will move the issue to the `Need technical help column`  for now.

**Comment by chrifro** [comment]
@jacobparis I guess you don't have any feedback? Would be great to get a quick thumbs up.


Anyway, is this ready to be merged @nisarhassan12? Let's merge it and address anything else in follow-ups.

**Pull request merged**
