### PR TITLE
Update the Screencasts. 

### LINKED ISSUE #1283: Update /screencasts and add a screencast index page
We want to improve the ratio of users visiting /screencasts and actually watching a screencast. As most users click on the first screencast, we decided to highlight that and thereby ease the choices for the user. Furthermore, we want to highlight all existing screencasts on our website and not lose users on YouTube. That's why we created the screencast index page.

[Mockup:](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj/Website?node-id=2774%3A650
New Screencasts (1)
)
Screencast-index (2)

Note: there are a few comments in the Figma mockup, helping to understand the mockup

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #1283

Deploy Preview: https://deploy-preview-1438--gitpod-kumquat.netlify.app/screencasts/getting-started-with-gitpod

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1438"></a>

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/1438"></a>

### CODE REVIEW

**Comment by mikenikles** [comment]
@nisarhassan12 is this still a draft or is it ready for review?

**Comment by nisarhassan12** [comment]
@mikenikles it is still a draft. I'm planning to fix this https://github.com/gitpod-io/website/issues/1283 as par of this PR and there is still a lot of stuff remaining.

**Comment by Cahllagerfeld** [comment]
grafik
It looks like the duration isn't set correctly. (At least for me) the duration always stays at 2mins although the actual video length differs 🤔

**Comment by Cahllagerfeld** [comment]
On `screencast`, the last one with `local-companion` contains `undefined`
grafik

**Comment by nisarhassan12** [comment]
@pawlean at the moment below each of the individual screencasts pages we are displaying up to 6 screencasts in the **Next up...** section. What do you think about it? i.e is it fine like this ? or do we want to reduce them to up to 3 ? or have 6 on the first one and 3 on the rest ? or something else ? 
image

**Review by ChristinFrohne — COMMENTED** [review]
Cool, thanks @nisarhassan12 ✨

Some comments:

- [x] could you adjust the size of the YouTube embed so there is no black margin when watching the video? (the current height is fine, just the width needs to be reduced)

- [ ] after clicking on "view next screenshot" the next video should be in the focus of the screen 

- [x]  please update the text of this section to the following
Bildschirmfoto 2022-01-17 um 11 12 39

- [x] something seems to be off in the "get started" call out. The images are outdated (the colors of the workspaces differ)

- [ ] on mobile: could you reduce the numbers of videos listed under "next up" to 3?

- [ ] on the index page: if the search doesn't find anything, let's display an error message "Sorry, we couldn't find any results matching your search."
- [ ] on the index page:  let's clear the search bar if a suggested topic is selected

- [ ] on the index page: to disable a suggested topic the user should need to click on the topic again. Currently, the results are cleared by clicking anywhere on the page which can be confusing
- [ ] currently, the text underneath the headline is a duplicate of the description underneath each video. Would there be anything else noteworthy to mention in the video description or should be remove the description underneath the video @pawlean ?

**Comment by nisarhassan12** [comment]
> could you adjust the size of the YouTube embed so there is no black margin when watching the video? (the current height is fine, just the width needs to be reduced)

@ChristinFrohne I have adjusted it will work totally fine for desktops but as we get to smaller screens it won't be the case there will be some small black margins.

**Comment by nisarhassan12** [comment]
> - [ ]  after clicking on "view next screenshot" the next video should be in the focus of the screen

@mikenikles I don't know how this can be achieved at the moment for some reason it does not scroll to the top of the next page after the navigation. I have seen other issues where the scroll does not work reliably and the navigation does not start from where it is expected to be #1303 specifies a few.

**Comment by pawlean** [comment]
@nisarhassan12 Can we include this screencast for OpenVSCode (https://www.youtube.com/watch?v=qGR7rgqjdiY)? It's not set up like the other ones (e.g. thumbnail) but it was a bit different compared to the others as it's not Gitpod product related.

**Review by pawlean — CHANGES_REQUESTED** [review]
Apart from the link I mentioned, this is looking sharp. Thanks Nisar!

**Comment by mikenikles** [comment]
> after clicking on "view next screenshot" the next video should be in the focus of the screen

@nisarhassan12 I fixed ☝️ in e866d81. When we navigate from one screencast to another, we use the same component and simply change the content. This means, Svelte does not re-render the component hence the default browser behaviour of scrolling to the top doesn't apply. The `afterNavigate` lifecycle function provided by SvelteKit's `$app/navigate` module lets us solve this by manually scrolling to the top.

**Pull request merged**
