### PR TITLE
improve quotes animation.

### LINKED ISSUE #2213: Improve quote animation
**Changes:**

- [x] increase the time between the quotes from 3sec to 10sec (see [Slack discussion](https://gitpod.slack.com/archives/C01KGM9ETU6/p1654850516901289))
- [x] smoothen the animation when switching between the quotes
- [x] on for /enterprise align the JetBrains logo with the standard dark theme style: grey by default, usual colors when active

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #2213 

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2222"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2222"></a>

### CODE REVIEW

**Comment by chrifro** [comment]
Thanks the timing works better now but the transition animation between the quotes is still a bit harsh. Could you have another look if you can smoothen it @nisarhassan12 ? 🙏

**Comment by nisarhassan12** [comment]
@chrifro I have updated the animation Please have another look. Thanks

**Comment by chrifro** [comment]
The text animation is nice, the image blur is way too much. It would be great to have a smoother transition when the quote card becomes bigger than usual. The switch on /enterprise between e.g. Redwoodjs and JetBrains is quite harsh

**Comment by nisarhassan12** [comment]
@chrifro I have removed the blur and used a different animation for the image. 

> It would be great to have a smoother transition when the quote card becomes bigger than usual.

Sorry, I tried multiple things but I'm unable to animate the height of the card when it becomes bigger. I'll open up a follow-up and try to address this later on.

**Comment by nisarhassan12** [comment]
@chrifro I have opened https://github.com/gitpod-io/website/issues/2319 to track the remaining todo I'm going to merge this Pr will hopefully address that in a follow up.

**Pull request merged**
