### PR TITLE
feat-page/java-panel-discussion

### LINKED ISSUE #2769: Create Panel Discussion Landing Page
Title : Success and failure stories of Java developers shifting to remote 
Date: October 4, 6 PM CEST

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
Preview on: [**this page**](https://deploy-preview-2770--gitpod-kumquat.netlify.app/webinars/java-panel-discussion)

fixes #2769 

TODO:
- [x] Add all Hosts names, images, description: @Nancy-Chauhan 
- [x] Update Title & Description & Time: @Nancy-Chauhan 
- [x] Update `Hosted by` logos: @nisarhassan12 
- [x] Update Registration form (checkboxes) & Test Integration: @nisarhassan12
- [x] Add Component/ SVGs of Hosts' Organization: @nisarhassan12 @chrifro
- [ ] Thumbnail Image for Panel Discussion: @chrifro 

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/2770"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2770"></a>

### CODE REVIEW

**Comment by chrifro** [comment]
Nice reuse of the JetBrain webinar landing page 🎯 ✨ Once we hosted several webinars, we can also create an overview page. 

This PR doesn't seem ready for review yet. Happy to review it once it is in a "ready to be implemented" state. Let me know in case you need any specific feedback before 🙌

**Comment by nisarhassan12** [comment]
>  Update Hosted by logos: @nisarhassan12

@Siddhant-K-code Can you provide me with the logos that we are supposed to be using here ?

**Comment by Siddhant-K-code** [comment]
> > Update Hosted by logos: @nisarhassan12
> 
> @Siddhant-K-code Can you provide me with the logos that we are supposed to be using here ?


image

I was talking about this logo, we just want the Gitpod logo here. ie. we don't want [this part](https://github.com/gitpod-io/website/blob/b5f147ed55c0934cc16ff0090ed3593a9f5b47f8/src/lib/components/webinars/header.svelte#L35) to be rendered on this new page. But it should be there on the old page of the first webinar. So, we have to make it generalized and re-use it as a prop maybe.

**Comment by Siddhant-K-code** [comment]
Hey, @chrifro can you please review this for now?

we are going to merge it, later on, we will update the Hosts Description & one another host (if needed - once we will get the confirmation)

We are merging it today, because it may create file conflicts & will get affected by code Freeze from next Monday (i.e. 26th Sept.)

> So, we want to merge the backend & other affected components' work (which is primary for other files too).

**Comment by chrifro** [comment]
Nice ✨ Some comments:

- [ ] let's change the text in the speaker's bio to "To be announced"
- [ ] decrease the logo size a bit and align it to the center of the line
Bildschirmfoto 2022-09-23 um 15 19 45

- [ ] the contact widget opens behind the form
Bildschirmfoto 2022-09-23 um 15 19 14

- [ ] follow our general style of sentence capitalization (everything is small except proper names and the sentence start)
Bildschirmfoto 2022-09-23 um 15 22 47

- [ ] this note needs a link to our privacy policy. You can just add "More on privacy policy"
Bildschirmfoto 2022-09-23 um 15 23 56

- [ ] update the "helpful resources" with resources that are relevant to the discussion (cc @Nancy-Chauhan )

**Comment by chrifro** [comment]
>We are merging it today, because it may create file conflicts & will get affected by code Freeze from next Monday (i.e. 26th Sept.)

But this won't affect website changes apart from docs. See [here](https://www.notion.so/gitpod/Docs-Code-Freeze-Start-End-ec6133595b4c4faf87a2a7f330e50ec2) @Siddhant-K-code 

> This only applies to changes to product documentation and it’s children in [/docs](https://www.gitpod.io/docs) and not to other pages like the homepage, pricing, enterprise, etc.

**Comment by Siddhant-K-code** [comment]
@chrifro Thanks for the review.
It is the problem everywhere (irrespective of these PR changes), I do not know how can I fix this overlap issue. & How should the fix look like?

image

@Cahllagerfeld please help us here 🙏🏼

**Comment by nisarhassan12** [comment]
I have fixed this issue https://github.com/gitpod-io/website/pull/2770#issuecomment-1256231442 via reverting the Pr that caused it in the first place see https://github.com/gitpod-io/website/issues/2440#issuecomment-1256436931 for more context.

**Comment by Siddhant-K-code** [comment]
> * [ ]  this note needs a link to our privacy policy. You can just add "More on privacy policy"

I think it is standard among all the pages. Also, it is a `label text` that needs extra CSS to get this done. We can skip this

**Review by Nancy-Chauhan — APPROVED** [review]

**Pull request merged**
