### PR TITLE
docs(selfhosted): restructure [merge after #746]

### PR DESCRIPTION
**Pull request by ghuntley**
Let's merge this after https://github.com/gitpod-io/website/pull/746

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/754"></a>

### CODE REVIEW

**Comment by JohannesLandgraf** [comment]
Netlify deploy is failing cc @ghuntley

**Comment by ghuntley** [comment]
> Netlify deploy is failing cc @ghuntley

🎗 `netlify.toml` needs updating for redirects

**Review by ghuntley — COMMENTED** [review]
> Netlify deploy is failing cc @ghuntley

🎗 `netlify.toml` redirects needs updating

**Comment by ghuntley** [comment]
Closing this out and migrating changes to a clean pull-request rather then resolve merge conflicts.

**Pull request closed without merging**
