### PR TITLE
Update GitLab logo

### PR DESCRIPTION
**Pull request by gtsiolis**
## Description

Logo update for GitLab, see [relevant blog post](https://about.gitlab.com/blog/2022/04/27/devops-is-at-the-center-of-gitlab/). 🍊 

Also, copied opacity from GitLab's logo to GitHub and Bitbucket logos, which may not be needed and could be removed altogether.

See also relevant changes in https://github.com/gitpod-io/gitpod/pull/9859. 🪂 

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/2001"></a>

| BEFORE | AFTER |
|-|-|
| providers-before | providers-after |

### CODE REVIEW

**Comment by gtsiolis** [comment]
@chrifro Could you take a look or forward this to someone on the team? 🏓

**Comment by gtsiolis** [comment]
Ready for review! 🏓

**Review by nisarhassan12 — APPROVED** [review]
Thanks @gtsiolis for the PR. It LGTM 👍🏿

**Comment by gtsiolis** [comment]
Thanks for taking a look, @nisarhassan12! 🏀

**Comment by chrifro** [comment]
Awesome, thank you both for fixing this ✨ Regarding the opacity, I will create a follow-up issue for that.

**Pull request merged**
