### PR TITLE
blog: add a blog for Apache APISIX

### PR DESCRIPTION
**Pull request by yzeng25**
## Description

Add a blog for using GitPod to develop Apache APISIX in a web browser.

TODO
1. image
2. teaser image

## Related Issue(s)

Fixes https://github.com/gitpod-io/website/issues/1533

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/1715"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1715"></a>

### CODE REVIEW

**Comment by yzeng25** [comment]
Hi @pawlean , would you take a look when available?

**Comment by pawlean** [comment]
> Hi @pawlean , would you take a look when available?

Thanks for the ping! I've CC'ed @mikenikles to this. Mike - this might be one for guides?

**Comment by yzeng25** [comment]
Hi @pawlean , do we have any update here?

**Comment by juzhiyuan** [comment]
Hi @mikenikles, could you please have a check?

**Comment by yzeng25** [comment]
Hi all,

Since this pull request did not receive enough feedback in certain amount of time, I would like to close it for now. For future collaborations, please reach out to @juzhiyuan  .

**Pull request closed without merging**
