### PR TITLE
fix: quick fix for the image path

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

Fixed the Path of `environment-variables-account-settings.png`

## Related Issue(s)

Fixes # n/a

## How to test

- Go to: https://github.com/gitpod-io/website/blob/main/gitpod/docs/environment-variables.md#using-the-account-settings
- Check, Image Attached is not rendering, because of the wrong path
- It is working now [here](https://github.com/Siddhant-K-code/website/blob/7b63aa179e1ac671700a3f9ecf42ae98b9d0408f/gitpod/docs/environment-variables.md#using-the-account-settings), will fix by this PR.

## Release Notes

```release-note
n/a
```

## Documentation

n/a

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/1458"></a>

### CODE REVIEW

**Comment by pawlean** [comment]
Great spot! Thanks, @Siddhant-K-code. Once the checks have passed, I'll approve. I know it isn't on the website specifically but still requires it for me to approve. 👍🏼

**Review by pawlean — APPROVED** [review]

**Comment by pawlean** [comment]
@Cahllagerfeld Any idea why the lighthouse test is failing?

**Comment by Cahllagerfeld** [comment]
> @Cahllagerfeld Any idea why the lighthouse test is failing?

As far as I understand, the Lighthouse-Action depends on the Netlify-Deployment and runs in a timeout, if the netlify deployment takes too long.

**Comment by Cahllagerfeld** [comment]
> 👷 Deploy request for _gitpod-kumquat_ pending review. [Visit the deploys page to approve it](https://app.netlify.com/sites/gitpod-kumquat/deploys)
> 
> 🔨 Explore the source changes: [7b63aa1](https://github.com/gitpod-io/website/commit/7b63aa179e1ac671700a3f9ecf42ae98b9d0408f)

Do you @pawlean or @nisarhassan12 have permissions to run this task here? This might be the reason

**Comment by Siddhant-K-code** [comment]
It will work now for sure. 🚀 

It is taking too long to respond/redirect because of extra `./` before `static/`

> I dont know why the deployment task takes so long though 🤔

**Comment by Siddhant-K-code** [comment]
Okay, Never mind 😢

**Comment by Siddhant-K-code** [comment]
So, In my recent change in commit https://github.com/gitpod-io/website/pull/1458/commits/e70c0c34f022a81f22b1073c0735608d02eceeca 

I am directly redirecting to `static` folder, since it is in the root dir.

**Comment by Cahllagerfeld** [comment]
I dont think its related to your changes. For me it looks like its a permission thing.. 🤔

**Comment by pawlean** [comment]
Yeah, I might not have permissions @Cahllagerfeld. Do you?

**Comment by nisarhassan12** [comment]
> Do you @pawlean or @nisarhassan12 have permissions to run this task here? This might be the reason

@Cahllagerfeld This is exactly the reason i.e Netlify deploy preview task have not ran thus no preview URL for the Lighthouse CI job. 

@mikenikles is the one who has the permission to approve the deploy preview requests for Netlify.

**Comment by nisarhassan12** [comment]
@Siddhant-K-code Thanks for the PR. If you look at https://app.netlify.com/sites/gitpod-kumquat/deploys/61dfe2ceb872bb0008350d6d it is failing and that is because of https://github.com/gitpod-io/website/pull/1458/commits/7b63aa179e1ac671700a3f9ecf42ae98b9d0408f i.e the image is no longer accessible for the site

If you visit: https://www.gitpod.io/docs/environment-variables#using-the-account-settings

You'll see that the image is displayed correctly. 

image

@mikenikles Do you know How can we make the images work both on GitHub and the website ? I guess we would have to update https://github.com/gitpod-io/website/blob/main/src/lib/utils/remark-set-image-path.js for that right ?

**Comment by mikenikles** [comment]
At the moment, images only render on the website and not when a Markdown file is viewed on GitHub. This is a bigger change that also impacts relative link URLs.

The change in this PR is not the correct solution. If you visit the `/docs/environment-variables` page in your developer environment, you see the following warning in the console:

```
files in the public directory are served at the root path.
Instead of /static/images/docs/beta/configure/environment-variables/environment-variables-account-settings.png, use /images/docs/beta/configure/environment-variables/environment-variables-account-settings.png.
```

As Nisar mentioned, if we want images to render on GitHub and on the website, we need to update the `src/lib/utils/remark-set-image-path.js` file.

However, due to #1393, let's hold off with any such changes for now. Once docs moved to the `gitpod-io/gitpod` repo, we can consider fixing image paths & relative URLs when viewing Markdown files on GitHub.

**Comment by gtsiolis** [comment]
Thanks @mikenikles and @nisarhassan12 for the insights! 🏀 

Thanks again @Siddhant-K-code for opening this! I agree with @mikenikles here but please do not let this discourage you from contributing to other areas of the product or the website. 🍭

**Pull request closed without merging**
